<?php

/*
 * Ensures the autoloader under test is loaded, whatever the load order is.
 *
 * wp-includes/autoload.php registers itself with spl_autoload_register() when it
 * is required, and `require_once` is a no-op once the file has been required, so
 * this safely ensures the registration regardless of whether the bootstrap has
 * already loaded it.
 */
require_once ABSPATH . WPINC . '/autoload.php';

/**
 * Tests for wp_autoload_class().
 *
 * Five concerns, one test each, and they are the five the class autoloader can
 * actually be wrong about: a mapped entry that does not name a readable file, a
 * name the map does not hold being answered anyway, a load that declares more or
 * less than the name it was asked for, a committed map that no longer describes
 * the tree, and a mapped file whose contents do not match what the map promises.
 *
 * @group load
 *
 * @covers ::wp_autoload_class
 */
class Tests_Load_wpAutoloadClass extends WP_UnitTestCase {

	/**
	 * Tests that every generated class map entry points at a readable file.
	 *
	 * A mapped value is resolved by the autoloader as `ABSPATH . $path`, so it
	 * has to be a forward slashed path relative to the WordPress root. Anything
	 * absolute, Windows style or traversing above the root would resolve to a
	 * file the autoloader cannot load.
	 *
	 * @dataProvider data_class_map_entries
	 *
	 * @param mixed $class_name The mapped class, interface or trait name.
	 * @param mixed $path       The mapped file path, relative to ABSPATH.
	 */
	public function test_class_map_entry_points_to_a_readable_file( $class_name, $path ) {
		$this->assertIsString( $class_name, 'Every class map name must be a string.' );
		$this->assertNotSame( '', $class_name, 'Every class map name must be a non-empty string.' );
		$this->assertIsString( $path, "The path mapped for {$class_name} must be a string." );
		$this->assertNotSame( '', $path, "The path mapped for {$class_name} must be a non-empty string." );

		$this->assertStringNotContainsString(
			'\\',
			$path,
			"The path mapped for {$class_name} must use forward slashes."
		);

		$this->assertStringStartsNotWith(
			'/',
			$path,
			"The path mapped for {$class_name} must be relative to ABSPATH."
		);

		$this->assertNotContains(
			'..',
			explode( '/', $path ),
			"The path mapped for {$class_name} must not traverse above the WordPress root."
		);

		/*
		 * Asserted as one canonical form rather than only as the sum of the checks
		 * above, because the autoloader refuses anything else outright: a value it
		 * does not recognise as canonical is a miss, so a mapped path that is merely
		 * plausible would be unreachable at runtime.
		 */
		$this->assertMatchesRegularExpression(
			self::get_class_map_path_pattern(),
			$path,
			"The path mapped for {$class_name} must be a canonical .php path below wp-includes/ or wp-admin/includes/, with non-empty segments that do not begin with a dot."
		);

		$this->assertTrue(
			is_readable( ABSPATH . $path ),
			"The file mapped for {$class_name} is not readable: {$path}."
		);
	}

	/**
	 * Data provider that returns one case per generated class map entry.
	 *
	 * Cases are keyed by the mapped name so that a failing entry identifies
	 * itself in the test output instead of hiding behind a numeric data set.
	 *
	 * The map is always read from disk. No entry is duplicated here, because the
	 * map is generated by the build and a copy kept in this file would drift.
	 *
	 * @return array[] Array of test cases, each holding a mapped name and its path.
	 */
	public function data_class_map_entries() {
		$class_map = self::get_class_map();
		$cases     = array();

		foreach ( $class_map as $class_name => $path ) {
			$label = is_string( $class_name ) ? $class_name : 'non-string name: ' . var_export( $class_name, true );

			$cases[ $label ] = array( $class_name, $path );
		}

		if ( empty( $cases ) ) {
			/*
			 * The generated class map is committed, so an unreadable or empty map
			 * is a real failure. Returning one case that cannot pass reports it,
			 * where an empty provider would leave the entry assertions below
			 * running against nothing.
			 */
			$cases['the generated class map is missing or empty'] = array( '', '' );
		}

		return $cases;
	}

	/**
	 * Tests that a name the class map does not hold is ignored without error.
	 *
	 * The autoloader has to leave every other registered autoloader its turn, so
	 * a miss returns without loading a file, raising an error or emitting
	 * output. The test configuration converts notices, warnings and deprecations
	 * into exceptions and fails on output, so this test fails if the handler is
	 * not silent on a miss.
	 *
	 * Three shapes of miss are exercised, because the handler declines them at
	 * three different points and a regression in any one of them is invisible in
	 * the others: a name that carries a core prefix but is absent from the map, a
	 * name outside the prefixes the handler prefilters on, and a name PHP itself
	 * could never resolve because it still carries a leading separator. The last
	 * one is repeated, the way a caller falling through from class_exists() to
	 * interface_exists() repeats it, because loading a file for an unresolvable
	 * name would raise a redeclaration error on the second pass.
	 */
	public function test_unmapped_name_is_ignored_without_error() {
		$class_map = self::get_class_map();

		$absent       = 'WP_Nonexistent_Class_' . md5( __METHOD__ );
		$non_core     = self::get_non_core_probe_name();
		$mapped       = self::get_loadable_class_map_names( $class_map, 1 );
		$unresolvable = array();

		$this->assertArrayNotHasKey(
			self::normalize_name( $absent ),
			$class_map,
			'The name used to test a class map miss must not be mapped.'
		);

		$this->assertArrayNotHasKey(
			self::normalize_name( $non_core ),
			$class_map,
			'The name used to test the prefilter must not be mapped.'
		);

		$this->assertFalse(
			self::matches_a_core_prefix( self::normalize_name( $non_core ), self::get_autoloader_core_prefixes() ),
			'The name used to test the prefilter must not carry a prefix the autoloader recognizes.'
		);

		$this->assertCount(
			1,
			$mapped,
			'The class map must offer an undeclared name to test the unresolvable spelling with.'
		);

		$files_before = count( get_included_files() );

		/*
		 * Called directly, so each silent return is proven for the handler itself
		 * rather than for PHP's own tolerance of an unresolvable name further up
		 * the SPL stack. The doubled separator is asked for twice.
		 */
		wp_autoload_class( $absent );
		wp_autoload_class( $non_core );
		wp_autoload_class( '\\\\' . $mapped[0] );
		wp_autoload_class( '\\\\' . $mapped[0] );

		$this->assertSame(
			$files_before,
			count( get_included_files() ),
			'A name the class map does not hold must not load a file, however it is spelled.'
		);

		foreach ( array( $absent, $non_core, $mapped[0] ) as $class_name ) {
			if ( self::is_symbol_declared( $class_name ) ) {
				$unresolvable[] = $class_name;
			}
		}

		$this->assertSame(
			array(),
			$unresolvable,
			'A miss must not declare the name it was asked for, and an unresolvable spelling must not declare the class behind it.'
		);

		// Repeated through the SPL stack, which is how the handler runs in production.
		$this->assertFalse(
			self::symbol_resolves( $absent ),
			'An unmapped name must stay unresolvable once every autoloader has had its turn.'
		);

		$this->assertFalse(
			self::symbol_resolves( $non_core ),
			'A name outside the core prefixes must stay unresolvable once every autoloader has had its turn.'
		);

		// Declining an unresolvable spelling must not cost the resolvable one its answer.
		$this->assertTrue(
			self::symbol_resolves( $mapped[0] ),
			'A mapped name must still resolve after an unresolvable spelling of it was declined.'
		);
	}

	/**
	 * Tests that loading a mapped name declares that name and no unrelated symbol.
	 *
	 * The load has to resolve the name it was asked for, and it may additionally
	 * declare the mapped file's parent class, the interfaces it implements and
	 * the traits it uses, because those are resolved while the file is being
	 * compiled. Any other newly declared symbol that is not itself in the class
	 * map fails the test.
	 *
	 * The same property is then asserted for every spelling PHP can hand the
	 * handler: PHP passes the name exactly as the reference site wrote it, minus
	 * the one leading separator a fully qualified reference carries, so a lookup
	 * that matched a single casing would leave `new wp_query()` and
	 * `new \WP_Query()` unresolved while `new WP_Query()` worked. Each spelling
	 * is exercised against a different undeclared name, so no case is answered by
	 * a class an earlier one already loaded.
	 */
	public function test_loading_a_mapped_name_declares_only_related_symbols() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$class_name = self::get_loadable_class_map_name( $class_map );

		if ( null === $class_name ) {
			/*
			 * Every mapped name is already declared, so there is nothing left to
			 * load. Assert the property that remains observable: the map has
			 * kept its promise for every name in it.
			 */
			$unresolved = array();

			foreach ( array_keys( $class_map ) as $mapped_name ) {
				if ( ! self::is_symbol_declared( $mapped_name ) ) {
					$unresolved[] = $mapped_name;
				}
			}

			$this->assertSame(
				array(),
				$unresolved,
				'Every mapped name must be declared once its file has been loaded.'
			);

			return;
		}

		$declared_before = self::get_declared_symbols();

		wp_autoload_class( $class_name );

		$declared_after = self::get_declared_symbols();

		$this->assertTrue(
			self::is_symbol_declared( $class_name ),
			"Loading the file mapped for {$class_name} must declare {$class_name}."
		);

		$unrelated = array();

		foreach ( array_diff( $declared_after, $declared_before ) as $symbol ) {
			if ( isset( $class_map[ $symbol ] ) ) {
				continue;
			}

			if ( self::is_related_symbol( $symbol, $class_name ) ) {
				continue;
			}

			$unrelated[] = $symbol;
		}

		$this->assertSame(
			array(),
			$unrelated,
			"Loading the file mapped for {$class_name} must not declare an unrelated symbol."
		);

		$spellings = array(
			'upper cased'       => 'strtoupper',
			'mixed cased'       => array( __CLASS__, 'alternate_case' ),
			'leading separator' => array( __CLASS__, 'prefix_separator' ),
		);

		$names = self::get_loadable_class_map_names( $class_map, count( $spellings ) );

		$this->assertCount(
			count( $spellings ),
			$names,
			'The class map must offer enough undeclared names to exercise every spelling.'
		);

		$unresolved = array();

		foreach ( array_values( $spellings ) as $index => $transform ) {
			$spelled = call_user_func( $transform, $names[ $index ] );

			wp_autoload_class( $spelled );

			if ( ! self::is_symbol_declared( $names[ $index ] ) ) {
				$unresolved[] = $spelled;
			}
		}

		$this->assertSame(
			array(),
			$unresolved,
			'Every spelling of a mapped name must reach the file it is mapped to.'
		);
	}

	/**
	 * Tests that the committed class map describes the tree it ships with.
	 *
	 * Three ways a committed map stops describing the tree are checked together,
	 * because each one silently un-maps a name rather than failing loudly. A path
	 * left behind by a moved or removed file, or one that resolves to a directory,
	 * makes the autoloader stop resolving the name it is mapped for. A key that is
	 * not lower cased is unreachable whatever the reference site writes, because
	 * wp_autoload_class() lower cases the name it is given before looking it up. A
	 * name outside the prefixes the handler prefilters on is declined before the
	 * map is ever consulted.
	 *
	 * Scope is decided by the canonical form the autoloader requires rather than by
	 * the prefix alone, because a prefix test on its own accepts a value that starts
	 * inside the tree and then leaves it again, such as `wp-includes/../wp-config.php`.
	 */
	public function test_class_map_contains_no_stale_paths() {
		$class_map = self::get_class_map();
		$prefixes  = self::get_autoloader_core_prefixes();

		$this->assertIsArray( $class_map, 'The generated class map must return an array.' );
		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );
		$this->assertNotEmpty(
			$prefixes,
			'The core prefix list must be readable from the $core_prefixes declaration in wp-includes/autoload.php.'
		);

		$outside_scope     = array();
		$not_a_file        = array();
		$not_lower_cased   = array();
		$not_prefilterable = array();

		foreach ( $class_map as $class_name => $path ) {
			if ( ! is_string( $path ) || ! preg_match( self::get_class_map_path_pattern(), $path ) ) {
				$outside_scope[] = $class_name;
			} elseif ( ! is_file( ABSPATH . $path ) ) {
				$not_a_file[] = $class_name . ' => ' . $path;
			}

			if ( ! is_string( $class_name ) || strtolower( $class_name ) !== $class_name ) {
				$not_lower_cased[] = var_export( $class_name, true );
				continue;
			}

			if ( ! self::matches_a_core_prefix( $class_name, $prefixes ) ) {
				$not_prefilterable[] = $class_name;
			}
		}

		$this->assertSame(
			array(),
			$outside_scope,
			'Every class map path must be a canonical .php path relative to ABSPATH, below wp-includes/ or wp-admin/includes/, with non-empty segments that do not begin with a dot.'
		);

		$this->assertSame(
			array(),
			$not_a_file,
			'Every class map path must name a file that exists.'
		);

		$this->assertSame(
			array(),
			$not_lower_cased,
			'Every class map name must be lower cased so that any casing of a reference reaches it.'
		);

		$this->assertSame(
			array(),
			$not_prefilterable,
			sprintf(
				'Every class map name must start with one of the prefixes the autoloader prefilters on (%s).',
				implode( ', ', $prefixes )
			)
		);
	}

	/**
	 * Tests that every mapped file declares the symbol it is mapped for, and only that.
	 *
	 * This is the consistency the map asserts about the source tree, and it is
	 * checked by reading the files rather than by loading them, so every entry is
	 * covered in one pass rather than only the ones a request happens to reach.
	 *
	 * The file-scope check belongs with it, because it is the same promise seen
	 * from the other side: an autoloaded file runs at the first reference to its
	 * symbol rather than at a fixed point in the load order, so anything it does
	 * beyond declaring that symbol happens at a moment the bootstrap has not
	 * agreed to. The scan is a conservative eligibility check - it recognises the
	 * top-level constructs a mapped file may hold and rejects anything else,
	 * which can reject a file that would in fact have been harmless.
	 */
	public function test_class_map_entries_declare_the_mapped_symbol() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$problems     = array();
		$side_effects = array();

		foreach ( $class_map as $class_name => $path ) {
			if ( ! is_string( $class_name ) || ! is_string( $path ) || ! is_readable( ABSPATH . $path ) ) {
				// Reported by test_class_map_entry_points_to_a_readable_file().
				continue;
			}

			$declared = self::get_declared_symbol_names( ABSPATH . $path );

			if ( 1 !== count( $declared ) ) {
				$problems[] = sprintf(
					'%s: mapped file declares %d symbols (%s)',
					$class_name,
					count( $declared ),
					implode( ', ', $declared )
				);
			} elseif ( ! self::names_match( $declared[0], $class_name ) ) {
				$problems[] = sprintf( '%s: mapped file declares %s', $class_name, $declared[0] );
			}

			$side_effect = self::get_file_scope_side_effect( ABSPATH . $path );

			if ( null !== $side_effect ) {
				$side_effects[] = $class_name . ' => ' . $path . ': ' . $side_effect;
			}
		}

		$this->assertSame(
			array(),
			$problems,
			'Every class map name must match the single class, interface or trait that its file declares.'
		);

		$this->assertSame(
			array(),
			$side_effects,
			'No mapped file may run anything at its own file scope.'
		);
	}

	/**
	 * Tests that the committed class map is the map the generator makes from the tree.
	 *
	 * The cases above check every entry the map holds. None of them can see an entry the
	 * map has *lost*: a name dropped from the map still leaves a well-formed map, the
	 * autoloader answers that name by doing nothing, and the failure surfaces much later
	 * as an undeclared class - and only on a request that references it, which for most of
	 * the mapped names is no request any test makes. Removing an entry for a class with no
	 * direct coverage therefore passed everything.
	 *
	 * Comparing against the generator closes that, because the generator is the only
	 * definition of what the map should hold: it walks the tree, applies the eligibility
	 * rules, and excludes what `wp-settings.php` already requires. Requiring it only
	 * defines its functions, so the map can be built here and compared without writing
	 * anything. Asserting equality rather than inclusion also catches the opposite defect:
	 * an entry the generator would not produce, such as one left behind for a file the
	 * bootstrap has since gone back to requiring, which would fatally redeclare its
	 * symbol.
	 *
	 * The generator is run against the source tree rather than against ABSPATH, because
	 * the committed map is a property of the committed tree and that is what has to hold
	 * whichever tree the suite happens to be installed from.
	 */
	public function test_class_map_is_the_map_the_generator_produces_from_the_tree() {
		$source_dir = dirname( untrailingslashit( ABSPATH ) ) . '/src/';
		$generator  = dirname( untrailingslashit( ABSPATH ) ) . '/tools/build/generate-autoload-classmap.php';
		$class_map  = $source_dir . 'wp-includes/autoload-classmap.php';

		if ( ! is_readable( $generator ) || ! is_readable( $class_map ) ) {
			$this->markTestSkipped( 'This test requires the development tree the class map is generated from.' );
		}

		require_once $generator;

		$this->assertTrue(
			function_exists( 'wp_autoload_classmap_build' ),
			'The class map generator must expose its build step without generating anything.'
		);

		$built     = wp_autoload_classmap_build( $source_dir );
		$committed = require $class_map;

		$this->assertIsArray( $committed, 'The committed class map must return an array.' );
		$this->assertNotEmpty( $committed, 'The committed class map must not be empty.' );

		$this->assertSame(
			array_keys( $built['map'] ),
			array_keys( $committed ),
			'The committed class map must hold exactly the names the generator produces from the source tree, in the same order. Run `grunt build:autoload-classmap` after changing wp-settings.php or adding a class file.'
		);

		$this->assertSame(
			$built['map'],
			$committed,
			'The committed class map must point every name at the file the generator resolves it to.'
		);
	}

	/**
	 * Returns the generated class map that wp_autoload_class() resolves against.
	 *
	 * Consumes the generated manifest the way core does elsewhere: a PHP file
	 * that returns an array, read with an assigned require behind a
	 * file_exists() guard and memoized for the rest of the run. The locator
	 * matches the one the autoloader uses, so both read the same file whether
	 * the tests run against the development tree or a built tree.
	 *
	 * @return array Map of class, interface and trait names to paths relative to
	 *               ABSPATH, or an empty array when the map is missing or does
	 *               not return an array.
	 */
	private static function get_class_map() {
		static $class_map = null;

		if ( null === $class_map ) {
			$class_map      = array();
			$class_map_file = ABSPATH . WPINC . '/autoload-classmap.php';

			if ( file_exists( $class_map_file ) ) {
				$map = require $class_map_file;

				if ( is_array( $map ) ) {
					$class_map = $map;
				}
			}
		}

		return $class_map;
	}

	/**
	 * Returns the form a class map path has to take.
	 *
	 * Stated here rather than read out of the autoloader, so that a change to the
	 * pattern the autoloader applies has to be made deliberately in both places.
	 * test_class_map_entry_points_to_a_readable_file() applies this copy to every
	 * committed entry.
	 *
	 * @return string Pattern for preg_match().
	 */
	private static function get_class_map_path_pattern() {
		return '#^(?:wp-includes|wp-admin/includes)/(?:[A-Za-z0-9_-][A-Za-z0-9_.-]*/)*[A-Za-z0-9_-][A-Za-z0-9_.-]*\.php$#';
	}

	/**
	 * Returns the prefixes the autoloader prefilters requested names on.
	 *
	 * Read out of the `$core_prefixes` declaration in the autoloader by
	 * tokenizing it, so the list is never duplicated here. Duplicating it would
	 * let the two copies drift, which is exactly the failure the tests using
	 * this helper exist to catch.
	 *
	 * @return string[] The declared prefixes, or an empty array when the
	 *                  declaration cannot be read.
	 */
	private static function get_autoloader_core_prefixes() {
		static $prefixes = null;

		if ( null !== $prefixes ) {
			return $prefixes;
		}

		$prefixes = array();
		$source   = file_get_contents( ABSPATH . WPINC . '/autoload.php' );

		if ( false === $source ) {
			return $prefixes;
		}

		$tokens    = token_get_all( $source );
		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT );

		for ( $index = 0; $index < $total; $index++ ) {
			if ( ! is_array( $tokens[ $index ] )
				|| T_VARIABLE !== $tokens[ $index ][0]
				|| '$core_prefixes' !== $tokens[ $index ][1]
			) {
				continue;
			}

			$assigned  = false;
			$depth     = 0;
			$collected = array();

			for ( $next = $index + 1; $next < $total; $next++ ) {
				$token = $tokens[ $next ];

				if ( is_array( $token ) ) {
					if ( in_array( $token[0], $ignorable, true ) ) {
						continue;
					}

					if ( $assigned && $depth > 0 && T_CONSTANT_ENCAPSED_STRING === $token[0] ) {
						$collected[] = trim( $token[1], '"\'' );
					}

					continue;
				}

				if ( ! $assigned ) {
					if ( '=' === $token ) {
						$assigned = true;
						continue;
					}

					// Not the declaration. Try the next occurrence of the variable.
					break;
				}

				if ( '(' === $token || '[' === $token ) {
					++$depth;
					continue;
				}

				if ( ')' === $token || ']' === $token ) {
					--$depth;

					if ( 0 === $depth ) {
						break;
					}

					continue;
				}

				if ( ';' === $token ) {
					break;
				}
			}

			if ( array() !== $collected ) {
				$prefixes = $collected;
				break;
			}
		}

		return $prefixes;
	}

	/**
	 * Determines whether a normalized name starts with one of the given prefixes.
	 *
	 * @param string   $name     Normalized symbol name.
	 * @param string[] $prefixes Normalized prefixes to test against.
	 * @return bool Whether the name starts with one of the prefixes.
	 */
	private static function matches_a_core_prefix( $name, $prefixes ) {
		foreach ( $prefixes as $prefix ) {
			if ( 0 === strncmp( $name, $prefix, strlen( $prefix ) ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Lower cases the ASCII letters of a symbol name.
	 *
	 * Mirrors the normalization the autoloader performs, character for
	 * character. strtr() is used rather than strtolower() for the same reason
	 * the autoloader uses it: strtolower() only stopped depending on the locale
	 * in PHP 8.2, and a Turkish locale folds `I` outside ASCII.
	 *
	 * @param string $name Symbol name.
	 * @return string The name with its ASCII letters lower cased.
	 */
	private static function normalize_name( $name ) {
		return strtr( $name, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz' );
	}

	/**
	 * Returns a probe name that lies outside the core prefixes.
	 *
	 * @return string A name outside the core prefixes.
	 */
	private static function get_non_core_probe_name() {
		return 'Vendor_Unmapped_Autoloader_Probe';
	}

	/**
	 * Returns the first mapped name that is not declared yet and is safe to load.
	 *
	 * @param array $class_map The generated class map.
	 * @return string|null A mapped name that can be loaded, or null when every
	 *                     mapped name is already declared or has to be skipped.
	 */
	private static function get_loadable_class_map_name( $class_map ) {
		$names = self::get_loadable_class_map_names( $class_map, 1 );

		return $names ? $names[0] : null;
	}

	/**
	 * Returns up to a given number of mapped names that are not declared yet.
	 *
	 * Used by the tests that have to prove the handler actually ran: a name that
	 * is already declared would report success without the autoloader being
	 * consulted at all.
	 *
	 * @param array $class_map The generated class map.
	 * @param int   $count     How many names to return.
	 * @return string[] Mapped names that can be loaded, at most $count of them.
	 */
	private static function get_loadable_class_map_names( $class_map, $count ) {
		$names = array();

		foreach ( $class_map as $class_name => $path ) {
			if ( count( $names ) >= $count ) {
				break;
			}

			if ( ! is_string( $class_name ) || ! is_string( $path ) ) {
				continue;
			}

			if ( self::is_symbol_declared( $class_name ) ) {
				continue;
			}

			if ( self::may_report_deprecation_on_load( ABSPATH . $path ) ) {
				continue;
			}

			$names[] = $class_name;
		}

		return $names;
	}

	/**
	 * Returns a name with the case of every other letter flipped.
	 *
	 * @param string $name Name to respell.
	 * @return string The respelled name.
	 */
	private static function alternate_case( $name ) {
		$respelled = '';

		for ( $index = 0, $length = strlen( $name ); $index < $length; $index++ ) {
			$respelled .= 0 === $index % 2 ? strtoupper( $name[ $index ] ) : strtolower( $name[ $index ] );
		}

		return $respelled;
	}

	/**
	 * Returns a name written with one leading namespace separator.
	 *
	 * @param string $name Name to qualify.
	 * @return string The qualified name.
	 */
	private static function prefix_separator( $name ) {
		return '\\' . $name;
	}

	/**
	 * Returns the names of every class, interface and trait declared so far.
	 *
	 * @return string[] Declared symbol names.
	 */
	private static function get_declared_symbols() {
		return array_merge( get_declared_classes(), get_declared_interfaces(), get_declared_traits() );
	}

	/**
	 * Determines whether a name is already declared, without triggering autoloading.
	 *
	 * The class map holds interfaces as well as classes, and spl_autoload_register()
	 * resolves interfaces and traits too, so all three symbol tables are checked.
	 *
	 * @param string $class_name Name to look for.
	 * @return bool Whether the name is declared.
	 */
	private static function is_symbol_declared( $class_name ) {
		return class_exists( $class_name, false )
			|| interface_exists( $class_name, false )
			|| trait_exists( $class_name, false );
	}

	/**
	 * Determines whether a name resolves, letting the registered autoloaders run.
	 *
	 * @param string $class_name Name to resolve.
	 * @return bool Whether the name resolves.
	 */
	private static function symbol_resolves( $class_name ) {
		return class_exists( $class_name )
			|| interface_exists( $class_name )
			|| trait_exists( $class_name );
	}

	/**
	 * Determines whether a symbol is the target itself or one of its relatives.
	 *
	 * A relative is a parent class or interface, an implemented interface or a
	 * used trait: all of them are resolved while the target is being compiled,
	 * so declaring them is an expected consequence of loading the target.
	 *
	 * @param string $symbol      Newly declared symbol name.
	 * @param string $target_name Name whose relatives are expected.
	 * @return bool Whether the symbol is expected.
	 */
	private static function is_related_symbol( $symbol, $target_name ) {
		if ( self::names_match( $symbol, $target_name ) ) {
			return true;
		}

		$relatives = array();

		foreach ( array( 'class_parents', 'class_implements', 'class_uses' ) as $relation ) {
			$found = $relation( $target_name, false );

			if ( is_array( $found ) ) {
				$relatives = array_merge( $relatives, array_keys( $found ) );
			}
		}

		foreach ( $relatives as $relative ) {
			if ( self::names_match( $symbol, $relative ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Compares two symbol names the way PHP resolves them.
	 *
	 * PHP matches class, interface and trait names case insensitively. A mapped
	 * name may be namespace qualified while the tokenizer only sees the short
	 * name in the declaration, so a match on the last segment counts too.
	 *
	 * @param string $declared_name Name taken from a declaration.
	 * @param string $mapped_name   Name taken from the class map.
	 * @return bool Whether the two names refer to the same symbol.
	 */
	private static function names_match( $declared_name, $mapped_name ) {
		if ( 0 === strcasecmp( $declared_name, $mapped_name ) ) {
			return true;
		}

		$segments = explode( '\\', $mapped_name );

		return 0 === strcasecmp( $declared_name, end( $segments ) );
	}

	/**
	 * Returns the class, interface and trait names declared in a file.
	 *
	 * The file is tokenized rather than loaded, so inspecting it has no side
	 * effect. A `::class` constant and an anonymous class are expressions rather
	 * than declarations, so neither is counted.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return string[] Declared names, in the order they appear in the file.
	 */
	private static function get_declared_symbol_names( $file ) {
		$names = array();

		foreach ( self::get_declared_symbols_with_kinds( $file ) as $symbol ) {
			$names[] = $symbol['name'];
		}

		return $names;
	}

	/**
	 * Returns the class, interface and trait declarations in a file, with their kind.
	 *
	 * Shares one tokenizer pass with get_declared_symbol_names(), so that both
	 * views of a file agree on what counts as a declaration.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return array[] {
	 *     Declarations, in the order they appear in the file.
	 *
	 *     @type array ...$0 {
	 *         @type string $kind One of 'class', 'interface' or 'trait'.
	 *         @type string $name The declared name.
	 *     }
	 * }
	 */
	private static function get_declared_symbols_with_kinds( $file ) {
		$tokens    = token_get_all( file_get_contents( $file ) );
		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT );
		$kinds     = array(
			T_CLASS     => 'class',
			T_INTERFACE => 'interface',
			T_TRAIT     => 'trait',
		);
		$declaring = array_keys( $kinds );
		$symbols   = array();

		for ( $index = 0; $index < $total; $index++ ) {
			if ( ! is_array( $tokens[ $index ] ) || ! in_array( $tokens[ $index ][0], $declaring, true ) ) {
				continue;
			}

			// `Foo::class` reads the name of a class, it does not declare one.
			$previous = $index - 1;

			while ( $previous >= 0 && is_array( $tokens[ $previous ] ) && in_array( $tokens[ $previous ][0], $ignorable, true ) ) {
				--$previous;
			}

			if ( $previous >= 0 && is_array( $tokens[ $previous ] ) && T_DOUBLE_COLON === $tokens[ $previous ][0] ) {
				continue;
			}

			// A declaration is followed by its name. An anonymous class is not.
			$next = $index + 1;

			while ( $next < $total && is_array( $tokens[ $next ] ) && in_array( $tokens[ $next ][0], $ignorable, true ) ) {
				++$next;
			}

			if ( $next < $total && is_array( $tokens[ $next ] ) && T_STRING === $tokens[ $next ][0] ) {
				$symbols[] = array(
					'kind' => $kinds[ $tokens[ $index ][0] ],
					'name' => $tokens[ $next ][1],
				);
			}
		}

		return $symbols;
	}

	/**
	 * Returns a description of the first statement a file runs at its own file scope.
	 *
	 * The file is tokenized rather than loaded, so inspecting it cannot trigger
	 * the very side effect being looked for. The classification is deliberately
	 * conservative: a class, interface or trait declaration, a namespace, an
	 * import, a `declare` and an attribute are recognised and skipped, and any
	 * other top-level construct is reported as executing. A construct that is in
	 * fact harmless - a function or constant declaration, for instance - is
	 * therefore reported too, which is a false positive this check accepts.
	 *
	 * Written without reference to how the class map generator classifies a file,
	 * so this side of the contract does not inherit that side's mistakes.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return string|null A description of the first executing statement, or null when there is none.
	 */
	private static function get_file_scope_side_effect( $file ) {
		$source = file_get_contents( $file );

		if ( ! is_string( $source ) ) {
			return 'the file could not be read';
		}

		$tokens = token_get_all( $source );

		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT, T_OPEN_TAG, T_CLOSE_TAG );
		$inert     = array( T_NAMESPACE, T_USE, T_DECLARE );
		$modifiers = array( T_ABSTRACT, T_FINAL );
		$declaring = array( T_CLASS, T_INTERFACE, T_TRAIT );

		if ( defined( 'T_ENUM' ) ) {
			$declaring[] = T_ENUM;
		}

		if ( defined( 'T_READONLY' ) ) {
			$modifiers[] = T_READONLY;
		}

		for ( $index = 0; $index < $total; $index++ ) {
			$token = $tokens[ $index ];

			if ( is_string( $token ) ) {
				if ( ';' === $token ) {
					continue;
				}

				return sprintf( '%s at the top level', $token );
			}

			if ( in_array( $token[0], $ignorable, true ) || in_array( $token[0], $modifiers, true ) ) {
				continue;
			}

			// An attribute annotates the declaration that follows it and runs nothing.
			if ( defined( 'T_ATTRIBUTE' ) && T_ATTRIBUTE === $token[0] ) {
				$index = self::skip_attribute( $tokens, $index ) - 1;
				continue;
			}

			// A namespace, an import and a `declare` end at their semicolon.
			if ( in_array( $token[0], $inert, true ) ) {
				for ( ++$index; $index < $total; $index++ ) {
					if ( is_string( $tokens[ $index ] ) && ';' === $tokens[ $index ] ) {
						break;
					}

					if ( is_string( $tokens[ $index ] ) && '{' === $tokens[ $index ] ) {
						return sprintf( '%s with a body at the top level', token_name( $token[0] ) );
					}
				}

				continue;
			}

			if ( in_array( $token[0], $declaring, true ) ) {
				$body = self::skip_declaration( $tokens, $index );

				if ( null === $body ) {
					return sprintf( 'an anonymous or malformed %s', strtolower( token_name( $token[0] ) ) );
				}

				$index = $body - 1;
				continue;
			}

			return sprintf( '%s on line %d', token_name( $token[0] ), $token[2] );
		}

		return null;
	}

	/**
	 * Returns the index of the first token after an attribute.
	 *
	 * @param array $tokens Token list from token_get_all().
	 * @param int   $index  Index of the T_ATTRIBUTE token.
	 * @return int Index of the first token after the attribute.
	 */
	private static function skip_attribute( $tokens, $index ) {
		$total = count( $tokens );
		$depth = 0;

		for ( ; $index < $total; $index++ ) {
			if ( is_array( $tokens[ $index ] ) ) {
				if ( defined( 'T_ATTRIBUTE' ) && T_ATTRIBUTE === $tokens[ $index ][0] ) {
					++$depth;
				}

				continue;
			}

			if ( '[' === $tokens[ $index ] ) {
				++$depth;
				continue;
			}

			if ( ']' === $tokens[ $index ] ) {
				--$depth;

				if ( 0 === $depth ) {
					return $index + 1;
				}
			}
		}

		return $total;
	}

	/**
	 * Returns the index of the first token after a declaration body.
	 *
	 * @param array $tokens Token list from token_get_all().
	 * @param int   $index  Index of the declaring keyword.
	 * @return int|null Index of the first token after the body, or null when the
	 *                  declaration is anonymous or carries no named declaration
	 *                  the scan recognises.
	 */
	private static function skip_declaration( $tokens, $index ) {
		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT );
		$cursor    = $index + 1;

		while ( $cursor < $total && is_array( $tokens[ $cursor ] ) && in_array( $tokens[ $cursor ][0], $ignorable, true ) ) {
			++$cursor;
		}

		if ( $cursor >= $total || ! is_array( $tokens[ $cursor ] ) || T_STRING !== $tokens[ $cursor ][0] ) {
			return null;
		}

		$depth = 0;

		for ( ; $cursor < $total; $cursor++ ) {
			if ( is_array( $tokens[ $cursor ] ) ) {
				if ( T_CURLY_OPEN === $tokens[ $cursor ][0]
					|| ( defined( 'T_DOLLAR_OPEN_CURLY_BRACES' ) && T_DOLLAR_OPEN_CURLY_BRACES === $tokens[ $cursor ][0] )
				) {
					++$depth;
				}

				continue;
			}

			if ( '{' === $tokens[ $cursor ] ) {
				++$depth;
				continue;
			}

			if ( '}' === $tokens[ $cursor ] ) {
				--$depth;

				if ( 0 === $depth ) {
					return $cursor + 1;
				}
			}
		}

		return $total;
	}

	/**
	 * Determines whether loading a file may report a deprecation.
	 *
	 * Conservatively skips files that reference a deprecation helper, because a
	 * deprecation raised while a file is being loaded is converted into an
	 * exception by the test configuration and belongs to the loaded file rather
	 * than to the autoloader.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return bool Whether the file has to be skipped.
	 */
	private static function may_report_deprecation_on_load( $file ) {
		if ( ! is_readable( $file ) ) {
			return true;
		}

		$source = file_get_contents( $file );
		$calls  = array(
			'_deprecated_file(',
			'_deprecated_class(',
			'_deprecated_function(',
			'trigger_error(',
		);

		foreach ( $calls as $call ) {
			if ( false !== strpos( $source, $call ) ) {
				return true;
			}
		}

		return false;
	}
}
