<?php

/*
 * Ensures the autoloader under test is loaded, whatever the load order is.
 *
 * wp-includes/autoload.php registers itself with spl_autoload_register() when it
 * is required, `require_once` is a no-op once the file has already been
 * required, and a repeat registration of the same named function is ignored, so
 * requiring it here is safe whether or not the bootstrap has loaded it already.
 */
require_once ABSPATH . WPINC . '/autoload.php';

/**
 * Tests for wp_autoload_class().
 *
 * @group load
 *
 * @covers ::wp_autoload_class
 */
class Tests_Load_wpAutoloadClass extends WP_UnitTestCase {

	/**
	 * Tests that every generated class map entry points at a readable file.
	 *
	 * A mapped value is resolved by the autoloader as `ABSPATH . $path`, so it
	 * has to be a forward slashed path relative to the WordPress root. Anything
	 * absolute, Windows style or traversing above the root would resolve to a
	 * file the autoloader cannot load.
	 *
	 * @dataProvider data_class_map_entries
	 *
	 * @param mixed $class_name The mapped class, interface or trait name.
	 * @param mixed $path       The mapped file path, relative to ABSPATH.
	 */
	public function test_class_map_entry_points_to_a_readable_file( $class_name, $path ) {
		$this->assertIsString( $class_name, 'Every class map name must be a string.' );
		$this->assertNotSame( '', $class_name, 'Every class map name must be a non-empty string.' );
		$this->assertIsString( $path, "The path mapped for {$class_name} must be a string." );
		$this->assertNotSame( '', $path, "The path mapped for {$class_name} must be a non-empty string." );

		$this->assertStringNotContainsString(
			'\\',
			$path,
			"The path mapped for {$class_name} must use forward slashes."
		);

		$this->assertStringStartsNotWith(
			'/',
			$path,
			"The path mapped for {$class_name} must be relative to ABSPATH."
		);

		$this->assertNotContains(
			'..',
			explode( '/', $path ),
			"The path mapped for {$class_name} must not traverse above the WordPress root."
		);

		$this->assertTrue(
			is_readable( ABSPATH . $path ),
			"The file mapped for {$class_name} is not readable: {$path}."
		);
	}

	/**
	 * Data provider that returns one case per generated class map entry.
	 *
	 * Cases are keyed by the mapped name so that a failing entry identifies
	 * itself in the test output instead of hiding behind a numeric data set.
	 *
	 * The map is always read from disk. No entry is duplicated here, because the
	 * map is generated by the build and a copy kept in this file would drift.
	 *
	 * @return array[] Array of test cases, each holding a mapped name and its path.
	 */
	public function data_class_map_entries() {
		$class_map = self::get_class_map();
		$cases     = array();

		foreach ( $class_map as $class_name => $path ) {
			$label = is_string( $class_name ) ? $class_name : 'non-string name: ' . var_export( $class_name, true );

			$cases[ $label ] = array( $class_name, $path );
		}

		if ( empty( $cases ) ) {
			/*
			 * The generated class map is committed, so an unreadable or empty map
			 * is a real failure. Returning one case that cannot pass reports it,
			 * where an empty provider would only mark the test risky.
			 */
			$cases['the generated class map is missing or empty'] = array( '', '' );
		}

		return $cases;
	}

	/**
	 * Tests that a name which is absent from the class map is ignored without error.
	 *
	 * The autoloader has to leave every other registered autoloader its turn, so
	 * a miss returns without loading a file, raising an error or emitting
	 * output. The test configuration converts notices, warnings and deprecations
	 * into exceptions and fails on output, so this test fails if the handler is
	 * not silent on a miss.
	 */
	public function test_unmapped_name_is_ignored_without_error() {
		$class_map  = self::get_class_map();
		$class_name = 'WP_Nonexistent_Class_' . md5( __METHOD__ );

		$this->assertArrayNotHasKey(
			$class_name,
			$class_map,
			'The name used to test a class map miss must not be mapped.'
		);

		$files_before = count( get_included_files() );

		/*
		 * Call the handler directly, so that the silent miss is proven for the
		 * handler itself rather than for PHP's own tolerance of an unresolvable
		 * name further up the SPL stack.
		 */
		wp_autoload_class( $class_name );

		$this->assertSame(
			$files_before,
			count( get_included_files() ),
			'A class map miss must not load a file.'
		);

		$this->assertFalse(
			self::is_symbol_declared( $class_name ),
			'A class map miss must not declare the requested name.'
		);

		// Repeat through the SPL stack, which is how the handler runs in production.
		$this->assertFalse(
			self::symbol_resolves( $class_name ),
			'An unmapped name must stay unresolvable once every autoloader has had its turn.'
		);
	}

	/**
	 * Tests that loading a mapped name declares that name and nothing unrelated.
	 *
	 * A mapped file is allowed to bring in its parent class, the interfaces it
	 * implements and the traits it uses, because those are resolved while the
	 * file is being compiled. Anything else means the file declares more than
	 * the single symbol it is mapped for.
	 */
	public function test_loading_a_mapped_name_declares_only_related_symbols() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$class_name = self::get_loadable_class_map_name( $class_map );

		if ( null === $class_name ) {
			/*
			 * Every mapped name is already declared, so there is nothing left to
			 * load. Assert the property that remains observable: the map has
			 * kept its promise for every name in it.
			 */
			$unresolved = array();

			foreach ( array_keys( $class_map ) as $mapped_name ) {
				if ( ! self::is_symbol_declared( $mapped_name ) ) {
					$unresolved[] = $mapped_name;
				}
			}

			$this->assertSame(
				array(),
				$unresolved,
				'Every mapped name must be declared once its file has been loaded.'
			);

			return;
		}

		$declared_before = self::get_declared_symbols();

		wp_autoload_class( $class_name );

		$declared_after = self::get_declared_symbols();

		$this->assertTrue(
			self::is_symbol_declared( $class_name ),
			"Loading the file mapped for {$class_name} must declare {$class_name}."
		);

		$unrelated = array();

		foreach ( array_diff( $declared_after, $declared_before ) as $symbol ) {
			if ( isset( $class_map[ $symbol ] ) ) {
				continue;
			}

			if ( self::is_related_symbol( $symbol, $class_name ) ) {
				continue;
			}

			$unrelated[] = $symbol;
		}

		$this->assertSame(
			array(),
			$unrelated,
			"Loading the file mapped for {$class_name} must not declare an unrelated symbol."
		);
	}

	/**
	 * Tests that the class map contains no stale or out of scope path.
	 *
	 * The generator maps files below wp-includes and, for the handful of classes
	 * the bootstrap used to load on every request, below wp-admin/includes. Every
	 * mapped value has to name a file that still exists: a path left behind by a
	 * moved or removed file, or one that resolves to a directory, would make the
	 * autoloader silently stop resolving the name it is mapped for.
	 */
	public function test_class_map_contains_no_stale_paths() {
		$class_map = self::get_class_map();

		$this->assertIsArray( $class_map, 'The generated class map must return an array.' );
		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$allowed_prefixes = array( 'wp-includes/', 'wp-admin/includes/' );
		$outside_scope    = array();
		$not_a_file       = array();

		foreach ( $class_map as $class_name => $path ) {
			$in_scope = false;

			if ( is_string( $path ) ) {
				foreach ( $allowed_prefixes as $prefix ) {
					if ( 0 === strpos( $path, $prefix ) ) {
						$in_scope = true;
						break;
					}
				}
			}

			if ( ! $in_scope ) {
				$outside_scope[] = $class_name;
				continue;
			}

			if ( ! is_file( ABSPATH . $path ) ) {
				$not_a_file[] = $class_name . ' => ' . $path;
			}
		}

		$this->assertSame(
			array(),
			$outside_scope,
			'Every class map path must be relative to ABSPATH and begin with wp-includes/ or wp-admin/includes/.'
		);

		$this->assertSame(
			array(),
			$not_a_file,
			'Every class map path must name a file that exists.'
		);
	}

	/**
	 * Tests that every class map name is lower cased.
	 *
	 * wp_autoload_class() lower cases the name it is given before looking it up,
	 * because PHP resolves class names case insensitively and hands the
	 * autoloader whatever casing the reference site used. A key that is not lower
	 * cased is therefore unreachable, no matter how the class is referenced.
	 */
	public function test_class_map_names_are_lower_cased() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$not_lower_cased = array();

		foreach ( array_keys( $class_map ) as $class_name ) {
			if ( ! is_string( $class_name ) || strtolower( $class_name ) !== $class_name ) {
				$not_lower_cased[] = var_export( $class_name, true );
			}
		}

		$this->assertSame(
			array(),
			$not_lower_cased,
			'Every class map name must be lower cased so that any casing of a reference reaches it.'
		);
	}

	/**
	 * Tests that a mapped name resolves however its reference is spelled.
	 *
	 * PHP passes the autoloader the name exactly as the reference site wrote it,
	 * minus the one leading separator a fully qualified reference carries. A
	 * lookup that only matched one casing would leave `new wp_query()` and
	 * `new \WP_Query()` silently unresolved while `new WP_Query()` worked.
	 *
	 * Each spelling is exercised against a different name that is not declared
	 * yet, so every case genuinely runs the handler rather than finding a class
	 * an earlier case already loaded.
	 */
	public function test_mapped_name_resolves_whatever_casing_is_used() {
		$class_map = self::get_class_map();
		$spellings = array(
			'as mapped'         => 'strval',
			'upper cased'       => 'strtoupper',
			'mixed cased'       => array( __CLASS__, 'alternate_case' ),
			'leading separator' => array( __CLASS__, 'prefix_separator' ),
		);

		$names = self::get_loadable_class_map_names( $class_map, count( $spellings ) );

		$this->assertCount(
			count( $spellings ),
			$names,
			'The class map must offer enough undeclared names to exercise every spelling.'
		);

		$unresolved = array();

		foreach ( array_values( $spellings ) as $index => $transform ) {
			$spelled = call_user_func( $transform, $names[ $index ] );

			wp_autoload_class( $spelled );

			if ( ! self::is_symbol_declared( $names[ $index ] ) ) {
				$unresolved[] = $spelled;
			}
		}

		$this->assertSame(
			array(),
			$unresolved,
			'Every spelling of a mapped name must reach the file it is mapped to.'
		);
	}

	/**
	 * Tests that a name PHP cannot resolve is left alone.
	 *
	 * PHP removes the one leading separator a fully qualified reference is
	 * written with before calling an autoloader, so a name that still starts with
	 * a separator when the handler sees it came from a direct spl_autoload_call()
	 * and names nothing PHP can match. Stripping a run of separators would make
	 * the handler load a file for a name that stays unresolvable, and then load
	 * it a second time when the caller fell through from class_exists() to
	 * interface_exists().
	 */
	public function test_lookup_ignores_a_name_with_a_doubled_leading_separator() {
		$class_map = self::get_class_map();
		$names     = self::get_loadable_class_map_names( $class_map, 1 );

		$this->assertCount( 1, $names, 'The class map must offer an undeclared name to test with.' );

		$files_before = count( get_included_files() );

		wp_autoload_class( '\\\\' . $names[0] );

		$this->assertSame(
			$files_before,
			count( get_included_files() ),
			'A name with a doubled leading separator must not load a file.'
		);

		$this->assertFalse(
			self::is_symbol_declared( $names[0] ),
			'A name with a doubled leading separator must not declare the underlying class.'
		);

		/*
		 * Repeat the call the way a caller falling through from class_exists() to
		 * interface_exists() would. Nothing may be loaded, and in particular the
		 * second pass may not raise a redeclaration error.
		 */
		wp_autoload_class( '\\\\' . $names[0] );

		$this->assertSame(
			$files_before,
			count( get_included_files() ),
			'Repeating the call must stay a no-op.'
		);

		// The same name written the way PHP writes it must still resolve.
		$this->assertTrue(
			self::symbol_resolves( $names[0] ),
			'Ignoring an unresolvable spelling must not stop the resolvable one from working.'
		);
	}

	/**
	 * Tests that no mapped file runs anything at its own file scope.
	 *
	 * This is the property that makes a mapped file safe to load from an
	 * autoloader. A file that requires its own subclasses at file scope recurses
	 * through the autoloader while its parent is still being declared, which
	 * exhausts the stack rather than raising an error; a file that reports a
	 * deprecation emits output in the middle of an unrelated request; and a file
	 * that calls a function assumes a bootstrap state the autoloader cannot
	 * promise, because it runs at the first reference rather than at a fixed
	 * point in the load order.
	 */
	public function test_class_map_entries_have_no_file_scope_side_effects() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$side_effects = array();

		foreach ( $class_map as $class_name => $path ) {
			if ( ! is_string( $path ) || ! is_readable( ABSPATH . $path ) ) {
				// Reported by test_class_map_entry_points_to_a_readable_file().
				continue;
			}

			$side_effect = self::get_file_scope_side_effect( ABSPATH . $path );

			if ( null !== $side_effect ) {
				$side_effects[] = $class_name . ' => ' . $path . ': ' . $side_effect;
			}
		}

		$this->assertSame(
			array(),
			$side_effects,
			'No mapped file may run anything at its own file scope.'
		);
	}

	/**
	 * Tests that the committed class map is what the generator produces.
	 *
	 * The map is a build artifact, so a hand edit or a source change made without
	 * rebuilding would leave it describing a tree that no longer exists. Because
	 * the generator is what enforces every eligibility rule, agreeing with it is
	 * also what keeps an ineligible file from being mapped by hand.
	 */
	public function test_class_map_matches_the_generator() {
		$generator = dirname( untrailingslashit( ABSPATH ) ) . '/tools/build/generate-autoload-classmap.php';

		$this->assertTrue(
			is_readable( $generator ),
			'The class map generator must be present at tools/build/generate-autoload-classmap.php.'
		);

		require_once $generator;

		$generated = wp_autoload_classmap_build( ABSPATH );

		$this->assertSame(
			$generated['map'],
			self::get_class_map(),
			'The committed class map must match the output of build:autoload-classmap. Run `grunt build:autoload-classmap`.'
		);
	}

	/**
	 * Tests that registering the handler again changes nothing.
	 *
	 * wp-includes/autoload.php is required with `require_once` from the bootstrap
	 * and again from this test file, and a plugin may require it as well. PHP
	 * ignores a repeated registration of the same named function, so the handler
	 * has to appear on the autoload stack exactly once however often it is
	 * registered, and resolution has to keep working afterwards.
	 */
	public function test_repeated_registration_is_harmless() {
		$occurrences = static function () {
			$found = 0;

			foreach ( (array) spl_autoload_functions() as $callable ) {
				if ( 'wp_autoload_class' === $callable ) {
					++$found;
				}
			}

			return $found;
		};

		$this->assertSame( 1, $occurrences(), 'The handler must be registered exactly once.' );

		spl_autoload_register( 'wp_autoload_class' );

		$this->assertSame( 1, $occurrences(), 'Registering the handler again must not add a second entry.' );

		$names = self::get_loadable_class_map_names( self::get_class_map(), 1 );

		$this->assertCount( 1, $names, 'The class map must offer an undeclared name to test with.' );

		$this->assertTrue(
			self::symbol_resolves( $names[0] ),
			'A mapped name must still resolve after a repeated registration.'
		);
	}

	/**
	 * Tests that an absent or unusable class map degrades to doing nothing.
	 *
	 * The map is read from a hard-coded path behind a file_exists() guard and its
	 * return value is only trusted when it is an array, so a tree without the
	 * generated map, or with a map that returns something else, has to resolve no
	 * name rather than raise an error. The map is memoized in the handler for the
	 * life of the request, so each case runs in its own process.
	 *
	 * @dataProvider data_unusable_class_maps
	 *
	 * @param string|null $contents Contents to write as the class map, or null to write no map at all.
	 */
	public function test_unusable_class_map_is_tolerated( $contents ) {
		$root = get_temp_dir() . 'wp-autoload-' . md5( __METHOD__ . serialize( $contents ) ) . '/';

		$this->assertTrue(
			wp_mkdir_p( $root . 'wp-includes' ),
			'The temporary tree for the test must be creatable.'
		);

		copy( ABSPATH . WPINC . '/autoload.php', $root . 'wp-includes/autoload.php' );

		if ( null !== $contents ) {
			file_put_contents( $root . 'wp-includes/autoload-classmap.php', $contents );
		}

		$script = sprintf(
			'define( "ABSPATH", %s ); define( "WPINC", "wp-includes" );'
				. ' require ABSPATH . WPINC . "/autoload.php";'
				. ' $found = class_exists( "WP_Query" ) || interface_exists( "WP_Query" );'
				. ' echo $found ? "resolved" : "unresolved";',
			var_export( $root, true )
		);

		$output    = array();
		$exit_code = 0;

		exec( escapeshellarg( PHP_BINARY ) . ' -d error_reporting=E_ALL -d display_errors=1 -r ' . escapeshellarg( $script ) . ' 2>&1', $output, $exit_code );

		// rmdir() only removes an empty directory, so the files have to go first.
		$this->rmdir( untrailingslashit( $root ) );
		$this->delete_folders( untrailingslashit( $root ) );

		$this->assertSame(
			0,
			$exit_code,
			'An unusable class map must not make the autoloader fail: ' . implode( "\n", $output )
		);

		$this->assertSame(
			array( 'unresolved' ),
			$output,
			'An unusable class map must resolve no name, silently.'
		);
	}

	/**
	 * Data provider for the unusable class map cases.
	 *
	 * @return array[] Array of test cases, each holding the contents to write, or null for no file.
	 */
	public function data_unusable_class_maps() {
		return array(
			'no class map at all'         => array( null ),
			'a map that returns nothing'  => array( "<?php\n" ),
			'a map that returns a string' => array( "<?php\nreturn 'not a map';\n" ),
			'a map that returns null'     => array( "<?php\nreturn null;\n" ),
			'an empty map'                => array( "<?php\nreturn array();\n" ),
		);
	}

	/**
	 * Tests that every mapped name is the single symbol its file declares.
	 *
	 * The map is inspected with the tokenizer rather than by loading each file,
	 * so that a side effect of a mapped file, such as the deprecation notice a
	 * deprecated shim reports when it is loaded, cannot influence the result.
	 */
	public function test_class_map_entries_declare_the_mapped_symbol() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$problems = array();

		foreach ( $class_map as $class_name => $path ) {
			if ( ! is_string( $class_name ) || ! is_string( $path ) || ! is_readable( ABSPATH . $path ) ) {
				// Reported by test_class_map_entry_points_to_a_readable_file().
				continue;
			}

			$declared = self::get_declared_symbol_names( ABSPATH . $path );

			if ( 1 !== count( $declared ) ) {
				$problems[] = sprintf(
					'%s: mapped file declares %d symbols (%s)',
					$class_name,
					count( $declared ),
					implode( ', ', $declared )
				);
				continue;
			}

			if ( ! self::names_match( $declared[0], $class_name ) ) {
				$problems[] = sprintf( '%s: mapped file declares %s', $class_name, $declared[0] );
			}
		}

		$this->assertSame(
			array(),
			$problems,
			'Every class map name must match the single class, interface or trait that its file declares.'
		);
	}

	/**
	 * Returns the generated class map that wp_autoload_class() resolves against.
	 *
	 * Consumes the generated manifest the way core does elsewhere: a PHP file
	 * that returns an array, read with an assigned require behind a
	 * file_exists() guard and memoized for the rest of the run. The locator
	 * matches the one the autoloader uses, so both read the same file whether
	 * the tests run against the development tree or a built tree.
	 *
	 * @return array Map of class, interface and trait names to paths relative to
	 *               ABSPATH, or an empty array when the map is missing or does
	 *               not return an array.
	 */
	private static function get_class_map() {
		static $class_map = null;

		if ( null === $class_map ) {
			$class_map      = array();
			$class_map_file = ABSPATH . WPINC . '/autoload-classmap.php';

			if ( file_exists( $class_map_file ) ) {
				$map = require $class_map_file;

				if ( is_array( $map ) ) {
					$class_map = $map;
				}
			}
		}

		return $class_map;
	}

	/**
	 * Returns the first mapped name that is not declared yet and is safe to load.
	 *
	 * @param array $class_map The generated class map.
	 * @return string|null A mapped name that can be loaded, or null when every
	 *                     mapped name is already declared or has to be skipped.
	 */
	private static function get_loadable_class_map_name( $class_map ) {
		$names = self::get_loadable_class_map_names( $class_map, 1 );

		return $names ? $names[0] : null;
	}

	/**
	 * Returns up to a given number of mapped names that are not declared yet.
	 *
	 * Used by the tests that have to prove the handler actually ran: a name that
	 * is already declared would report success without the autoloader being
	 * consulted at all.
	 *
	 * @param array $class_map The generated class map.
	 * @param int   $count     How many names to return.
	 * @return string[] Mapped names that can be loaded, at most $count of them.
	 */
	private static function get_loadable_class_map_names( $class_map, $count ) {
		$names = array();

		foreach ( $class_map as $class_name => $path ) {
			if ( count( $names ) >= $count ) {
				break;
			}

			if ( ! is_string( $class_name ) || ! is_string( $path ) ) {
				continue;
			}

			if ( self::is_symbol_declared( $class_name ) ) {
				continue;
			}

			if ( self::may_report_deprecation_on_load( ABSPATH . $path ) ) {
				continue;
			}

			$names[] = $class_name;
		}

		return $names;
	}

	/**
	 * Returns a name with the case of every other letter flipped.
	 *
	 * @param string $name Name to respell.
	 * @return string The respelled name.
	 */
	private static function alternate_case( $name ) {
		$respelled = '';

		for ( $index = 0, $length = strlen( $name ); $index < $length; $index++ ) {
			$respelled .= 0 === $index % 2 ? strtoupper( $name[ $index ] ) : strtolower( $name[ $index ] );
		}

		return $respelled;
	}

	/**
	 * Returns a name written with one leading namespace separator.
	 *
	 * @param string $name Name to qualify.
	 * @return string The qualified name.
	 */
	private static function prefix_separator( $name ) {
		return '\\' . $name;
	}

	/**
	 * Returns a description of the first statement a file runs at its own file scope.
	 *
	 * The file is tokenized rather than loaded, so inspecting it cannot trigger
	 * the very side effect being looked for. Only a declaration, a namespace, an
	 * import, a `declare` and an attribute are inert at the top level; anything
	 * else, from a `require` through an `if` to a bare function call, executes.
	 *
	 * Written independently of the generator on purpose: two implementations that
	 * agree is a stronger guarantee than one implementation checking itself.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return string|null A description of the first executing statement, or null when there is none.
	 */
	private static function get_file_scope_side_effect( $file ) {
		$source = file_get_contents( $file );

		if ( ! is_string( $source ) ) {
			return 'the file could not be read';
		}

		$tokens = token_get_all( $source );

		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT, T_OPEN_TAG, T_CLOSE_TAG );
		$inert     = array( T_NAMESPACE, T_USE, T_DECLARE );
		$modifiers = array( T_ABSTRACT, T_FINAL );
		$declaring = array( T_CLASS, T_INTERFACE, T_TRAIT );

		if ( defined( 'T_ENUM' ) ) {
			$declaring[] = T_ENUM;
		}

		if ( defined( 'T_READONLY' ) ) {
			$modifiers[] = T_READONLY;
		}

		for ( $index = 0; $index < $total; $index++ ) {
			$token = $tokens[ $index ];

			if ( is_string( $token ) ) {
				if ( ';' === $token ) {
					continue;
				}

				return sprintf( '%s at the top level', $token );
			}

			if ( in_array( $token[0], $ignorable, true ) || in_array( $token[0], $modifiers, true ) ) {
				continue;
			}

			// An attribute annotates the declaration that follows it and runs nothing.
			if ( defined( 'T_ATTRIBUTE' ) && T_ATTRIBUTE === $token[0] ) {
				$index = self::skip_attribute( $tokens, $index ) - 1;
				continue;
			}

			// A namespace, an import and a `declare` end at their semicolon.
			if ( in_array( $token[0], $inert, true ) ) {
				for ( ++$index; $index < $total; $index++ ) {
					if ( is_string( $tokens[ $index ] ) && ';' === $tokens[ $index ] ) {
						break;
					}

					if ( is_string( $tokens[ $index ] ) && '{' === $tokens[ $index ] ) {
						return sprintf( '%s with a body at the top level', token_name( $token[0] ) );
					}
				}

				continue;
			}

			if ( in_array( $token[0], $declaring, true ) ) {
				$body = self::skip_declaration( $tokens, $index );

				if ( null === $body ) {
					return sprintf( 'an anonymous or malformed %s', strtolower( token_name( $token[0] ) ) );
				}

				$index = $body - 1;
				continue;
			}

			return sprintf( '%s on line %d', token_name( $token[0] ), $token[2] );
		}

		return null;
	}

	/**
	 * Returns the index of the first token after an attribute.
	 *
	 * @param array $tokens Token list from token_get_all().
	 * @param int   $index  Index of the T_ATTRIBUTE token.
	 * @return int Index of the first token after the attribute.
	 */
	private static function skip_attribute( $tokens, $index ) {
		$total = count( $tokens );
		$depth = 0;

		for ( ; $index < $total; $index++ ) {
			if ( is_array( $tokens[ $index ] ) ) {
				if ( defined( 'T_ATTRIBUTE' ) && T_ATTRIBUTE === $tokens[ $index ][0] ) {
					++$depth;
				}

				continue;
			}

			if ( '[' === $tokens[ $index ] ) {
				++$depth;
				continue;
			}

			if ( ']' === $tokens[ $index ] ) {
				--$depth;

				if ( 0 === $depth ) {
					return $index + 1;
				}
			}
		}

		return $total;
	}

	/**
	 * Returns the index of the first token after a declaration body.
	 *
	 * @param array $tokens Token list from token_get_all().
	 * @param int   $index  Index of the declaring keyword.
	 * @return int|null Index of the first token after the body, or null when the declaration is anonymous.
	 */
	private static function skip_declaration( $tokens, $index ) {
		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT );
		$cursor    = $index + 1;

		while ( $cursor < $total && is_array( $tokens[ $cursor ] ) && in_array( $tokens[ $cursor ][0], $ignorable, true ) ) {
			++$cursor;
		}

		if ( $cursor >= $total || ! is_array( $tokens[ $cursor ] ) || T_STRING !== $tokens[ $cursor ][0] ) {
			return null;
		}

		$depth = 0;

		for ( ; $cursor < $total; $cursor++ ) {
			if ( is_array( $tokens[ $cursor ] ) ) {
				if ( T_CURLY_OPEN === $tokens[ $cursor ][0]
					|| ( defined( 'T_DOLLAR_OPEN_CURLY_BRACES' ) && T_DOLLAR_OPEN_CURLY_BRACES === $tokens[ $cursor ][0] )
				) {
					++$depth;
				}

				continue;
			}

			if ( '{' === $tokens[ $cursor ] ) {
				++$depth;
				continue;
			}

			if ( '}' === $tokens[ $cursor ] ) {
				--$depth;

				if ( 0 === $depth ) {
					return $cursor + 1;
				}
			}
		}

		return $total;
	}

	/**
	 * Determines whether loading a file may report a deprecation.
	 *
	 * Deliberately conservative: a file is skipped when it so much as mentions
	 * one of the deprecation helpers, because a deprecation raised while a file
	 * is being loaded is converted into an exception by the test configuration
	 * and belongs to the loaded file rather than to the autoloader.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return bool Whether the file has to be skipped.
	 */
	private static function may_report_deprecation_on_load( $file ) {
		if ( ! is_readable( $file ) ) {
			return true;
		}

		$source = file_get_contents( $file );
		$calls  = array(
			'_deprecated_file(',
			'_deprecated_class(',
			'_deprecated_function(',
			'trigger_error(',
		);

		foreach ( $calls as $call ) {
			if ( false !== strpos( $source, $call ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Returns the names of every class, interface and trait declared so far.
	 *
	 * @return string[] Declared symbol names.
	 */
	private static function get_declared_symbols() {
		return array_merge( get_declared_classes(), get_declared_interfaces(), get_declared_traits() );
	}

	/**
	 * Determines whether a name is already declared, without triggering autoloading.
	 *
	 * The class map holds interfaces as well as classes, and spl_autoload_register()
	 * resolves interfaces and traits too, so all three symbol tables are checked.
	 *
	 * @param string $class_name Name to look for.
	 * @return bool Whether the name is declared.
	 */
	private static function is_symbol_declared( $class_name ) {
		return class_exists( $class_name, false )
			|| interface_exists( $class_name, false )
			|| trait_exists( $class_name, false );
	}

	/**
	 * Determines whether a name resolves, letting the registered autoloaders run.
	 *
	 * @param string $class_name Name to resolve.
	 * @return bool Whether the name resolves.
	 */
	private static function symbol_resolves( $class_name ) {
		return class_exists( $class_name )
			|| interface_exists( $class_name )
			|| trait_exists( $class_name );
	}

	/**
	 * Determines whether a symbol is the target itself or one of its relatives.
	 *
	 * A relative is a parent class or interface, an implemented interface or a
	 * used trait: all of them are resolved while the target is being compiled,
	 * so declaring them is an expected consequence of loading the target.
	 *
	 * @param string $symbol      Newly declared symbol name.
	 * @param string $target_name Name whose relatives are expected.
	 * @return bool Whether the symbol is expected.
	 */
	private static function is_related_symbol( $symbol, $target_name ) {
		if ( self::names_match( $symbol, $target_name ) ) {
			return true;
		}

		$relatives = array();

		foreach ( array( 'class_parents', 'class_implements', 'class_uses' ) as $relation ) {
			$found = $relation( $target_name, false );

			if ( is_array( $found ) ) {
				$relatives = array_merge( $relatives, array_keys( $found ) );
			}
		}

		foreach ( $relatives as $relative ) {
			if ( self::names_match( $symbol, $relative ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Compares two symbol names the way PHP resolves them.
	 *
	 * PHP matches class, interface and trait names case insensitively. A mapped
	 * name may be namespace qualified while the tokenizer only sees the short
	 * name in the declaration, so a match on the last segment counts too.
	 *
	 * @param string $declared_name Name taken from a declaration.
	 * @param string $mapped_name   Name taken from the class map.
	 * @return bool Whether the two names refer to the same symbol.
	 */
	private static function names_match( $declared_name, $mapped_name ) {
		if ( 0 === strcasecmp( $declared_name, $mapped_name ) ) {
			return true;
		}

		$segments = explode( '\\', $mapped_name );

		return 0 === strcasecmp( $declared_name, end( $segments ) );
	}

	/**
	 * Returns the class, interface and trait names declared in a file.
	 *
	 * The file is tokenized rather than loaded, so inspecting it has no side
	 * effect. A `::class` constant and an anonymous class are expressions rather
	 * than declarations, so neither is counted.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return string[] Declared names, in the order they appear in the file.
	 */
	private static function get_declared_symbol_names( $file ) {
		$tokens    = token_get_all( file_get_contents( $file ) );
		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT );
		$declaring = array( T_CLASS, T_INTERFACE, T_TRAIT );
		$names     = array();

		for ( $index = 0; $index < $total; $index++ ) {
			if ( ! is_array( $tokens[ $index ] ) || ! in_array( $tokens[ $index ][0], $declaring, true ) ) {
				continue;
			}

			// `Foo::class` reads the name of a class, it does not declare one.
			$previous = $index - 1;

			while ( $previous >= 0 && is_array( $tokens[ $previous ] ) && in_array( $tokens[ $previous ][0], $ignorable, true ) ) {
				--$previous;
			}

			if ( $previous >= 0 && is_array( $tokens[ $previous ] ) && T_DOUBLE_COLON === $tokens[ $previous ][0] ) {
				continue;
			}

			// A declaration is followed by its name. An anonymous class is not.
			$next = $index + 1;

			while ( $next < $total && is_array( $tokens[ $next ] ) && in_array( $tokens[ $next ][0], $ignorable, true ) ) {
				++$next;
			}

			if ( $next < $total && is_array( $tokens[ $next ] ) && T_STRING === $tokens[ $next ][0] ) {
				$names[] = $tokens[ $next ][1];
			}
		}

		return $names;
	}
}
