<?php

/*
 * Ensures the autoloader under test is loaded, whatever the load order is.
 *
 * wp-includes/autoload.php registers itself with spl_autoload_register() when it
 * is required, `require_once` is a no-op once the file has already been
 * required, and a repeat registration of the same named function is ignored, so
 * requiring it here is safe whether or not the bootstrap has loaded it already.
 */
require_once ABSPATH . WPINC . '/autoload.php';

/**
 * Tests for wp_autoload_class().
 *
 * @group load
 *
 * @covers ::wp_autoload_class
 */
class Tests_Load_wpAutoloadClass extends WP_UnitTestCase {

	/**
	 * Tests that every generated class map entry points at a readable file.
	 *
	 * A mapped value is resolved by the autoloader as `ABSPATH . $path`, so it
	 * has to be a forward slashed path relative to the WordPress root. Anything
	 * absolute, Windows style or traversing above the root would resolve to a
	 * file the autoloader cannot load.
	 *
	 * @dataProvider data_class_map_entries
	 *
	 * @param mixed $class_name The mapped class, interface or trait name.
	 * @param mixed $path       The mapped file path, relative to ABSPATH.
	 */
	public function test_class_map_entry_points_to_a_readable_file( $class_name, $path ) {
		$this->assertIsString( $class_name, 'Every class map name must be a string.' );
		$this->assertNotSame( '', $class_name, 'Every class map name must be a non-empty string.' );
		$this->assertIsString( $path, "The path mapped for {$class_name} must be a string." );
		$this->assertNotSame( '', $path, "The path mapped for {$class_name} must be a non-empty string." );

		$this->assertStringNotContainsString(
			'\\',
			$path,
			"The path mapped for {$class_name} must use forward slashes."
		);

		$this->assertStringStartsNotWith(
			'/',
			$path,
			"The path mapped for {$class_name} must be relative to ABSPATH."
		);

		$this->assertNotContains(
			'..',
			explode( '/', $path ),
			"The path mapped for {$class_name} must not traverse above the WordPress root."
		);

		$this->assertTrue(
			is_readable( ABSPATH . $path ),
			"The file mapped for {$class_name} is not readable: {$path}."
		);
	}

	/**
	 * Data provider that returns one case per generated class map entry.
	 *
	 * Cases are keyed by the mapped name so that a failing entry identifies
	 * itself in the test output instead of hiding behind a numeric data set.
	 *
	 * The map is always read from disk. No entry is duplicated here, because the
	 * map is generated by the build and a copy kept in this file would drift.
	 *
	 * @return array[] Array of test cases, each holding a mapped name and its path.
	 */
	public function data_class_map_entries() {
		$class_map = self::get_class_map();
		$cases     = array();

		foreach ( $class_map as $class_name => $path ) {
			$label = is_string( $class_name ) ? $class_name : 'non-string name: ' . var_export( $class_name, true );

			$cases[ $label ] = array( $class_name, $path );
		}

		if ( empty( $cases ) ) {
			/*
			 * The generated class map is committed, so an unreadable or empty map
			 * is a real failure. Returning one case that cannot pass reports it,
			 * where an empty provider would only mark the test risky.
			 */
			$cases['the generated class map is missing or empty'] = array( '', '' );
		}

		return $cases;
	}

	/**
	 * Tests that a name which is absent from the class map is ignored without error.
	 *
	 * The autoloader has to leave every other registered autoloader its turn, so
	 * a miss returns without loading a file, raising an error or emitting
	 * output. The test configuration converts notices, warnings and deprecations
	 * into exceptions and fails on output, so this test fails if the handler is
	 * not silent on a miss.
	 */
	public function test_unmapped_name_is_ignored_without_error() {
		$class_map  = self::get_class_map();
		$class_name = 'WP_Nonexistent_Class_' . md5( __METHOD__ );

		$this->assertArrayNotHasKey(
			$class_name,
			$class_map,
			'The name used to test a class map miss must not be mapped.'
		);

		$files_before = count( get_included_files() );

		/*
		 * Call the handler directly, so that the silent miss is proven for the
		 * handler itself rather than for PHP's own tolerance of an unresolvable
		 * name further up the SPL stack.
		 */
		wp_autoload_class( $class_name );

		$this->assertSame(
			$files_before,
			count( get_included_files() ),
			'A class map miss must not load a file.'
		);

		$this->assertFalse(
			self::is_symbol_declared( $class_name ),
			'A class map miss must not declare the requested name.'
		);

		// Repeat through the SPL stack, which is how the handler runs in production.
		$this->assertFalse(
			self::symbol_resolves( $class_name ),
			'An unmapped name must stay unresolvable once every autoloader has had its turn.'
		);
	}

	/**
	 * Tests that loading a mapped name declares that name and nothing unrelated.
	 *
	 * A mapped file is allowed to bring in its parent class, the interfaces it
	 * implements and the traits it uses, because those are resolved while the
	 * file is being compiled. Anything else means the file declares more than
	 * the single symbol it is mapped for.
	 */
	public function test_loading_a_mapped_name_declares_only_related_symbols() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$class_name = self::get_loadable_class_map_name( $class_map );

		if ( null === $class_name ) {
			/*
			 * Every mapped name is already declared, so there is nothing left to
			 * load. Assert the property that remains observable: the map has
			 * kept its promise for every name in it.
			 */
			$unresolved = array();

			foreach ( array_keys( $class_map ) as $mapped_name ) {
				if ( ! self::is_symbol_declared( $mapped_name ) ) {
					$unresolved[] = $mapped_name;
				}
			}

			$this->assertSame(
				array(),
				$unresolved,
				'Every mapped name must be declared once its file has been loaded.'
			);

			return;
		}

		$declared_before = self::get_declared_symbols();

		wp_autoload_class( $class_name );

		$declared_after = self::get_declared_symbols();

		$this->assertTrue(
			self::is_symbol_declared( $class_name ),
			"Loading the file mapped for {$class_name} must declare {$class_name}."
		);

		$unrelated = array();

		foreach ( array_diff( $declared_after, $declared_before ) as $symbol ) {
			if ( isset( $class_map[ $symbol ] ) ) {
				continue;
			}

			if ( self::is_related_symbol( $symbol, $class_name ) ) {
				continue;
			}

			$unrelated[] = $symbol;
		}

		$this->assertSame(
			array(),
			$unrelated,
			"Loading the file mapped for {$class_name} must not declare an unrelated symbol."
		);
	}

	/**
	 * Tests that the class map contains no stale or out of scope path.
	 *
	 * The generator maps files below wp-includes and, for the handful of classes
	 * the bootstrap used to load on every request, below wp-admin/includes. Every
	 * mapped value has to name a file that still exists: a path left behind by a
	 * moved or removed file, or one that resolves to a directory, would make the
	 * autoloader silently stop resolving the name it is mapped for.
	 */
	public function test_class_map_contains_no_stale_paths() {
		$class_map = self::get_class_map();

		$this->assertIsArray( $class_map, 'The generated class map must return an array.' );
		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$allowed_prefixes = array( 'wp-includes/', 'wp-admin/includes/' );
		$outside_scope    = array();
		$not_a_file       = array();

		foreach ( $class_map as $class_name => $path ) {
			$in_scope = false;

			if ( is_string( $path ) ) {
				foreach ( $allowed_prefixes as $prefix ) {
					if ( 0 === strpos( $path, $prefix ) ) {
						$in_scope = true;
						break;
					}
				}
			}

			if ( ! $in_scope ) {
				$outside_scope[] = $class_name;
				continue;
			}

			if ( ! is_file( ABSPATH . $path ) ) {
				$not_a_file[] = $class_name . ' => ' . $path;
			}
		}

		$this->assertSame(
			array(),
			$outside_scope,
			'Every class map path must be relative to ABSPATH and begin with wp-includes/ or wp-admin/includes/.'
		);

		$this->assertSame(
			array(),
			$not_a_file,
			'Every class map path must name a file that exists.'
		);
	}

	/**
	 * Tests that every class map name is lower cased.
	 *
	 * wp_autoload_class() lower cases the name it is given before looking it up,
	 * because PHP resolves class names case insensitively and hands the
	 * autoloader whatever casing the reference site used. A key that is not lower
	 * cased is therefore unreachable, no matter how the class is referenced.
	 */
	public function test_class_map_names_are_lower_cased() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$not_lower_cased = array();

		foreach ( array_keys( $class_map ) as $class_name ) {
			if ( ! is_string( $class_name ) || strtolower( $class_name ) !== $class_name ) {
				$not_lower_cased[] = var_export( $class_name, true );
			}
		}

		$this->assertSame(
			array(),
			$not_lower_cased,
			'Every class map name must be lower cased so that any casing of a reference reaches it.'
		);
	}

	/**
	 * Tests that a mapped name resolves however its reference is spelled.
	 *
	 * PHP passes the autoloader the name exactly as the reference site wrote it,
	 * minus the one leading separator a fully qualified reference carries. A
	 * lookup that only matched one casing would leave `new wp_query()` and
	 * `new \WP_Query()` silently unresolved while `new WP_Query()` worked.
	 *
	 * Each spelling is exercised against a different name that is not declared
	 * yet, so every case genuinely runs the handler rather than finding a class
	 * an earlier case already loaded.
	 */
	public function test_mapped_name_resolves_whatever_casing_is_used() {
		$class_map = self::get_class_map();
		$spellings = array(
			'as mapped'         => 'strval',
			'upper cased'       => 'strtoupper',
			'mixed cased'       => array( __CLASS__, 'alternate_case' ),
			'leading separator' => array( __CLASS__, 'prefix_separator' ),
		);

		$names = self::get_loadable_class_map_names( $class_map, count( $spellings ) );

		$this->assertCount(
			count( $spellings ),
			$names,
			'The class map must offer enough undeclared names to exercise every spelling.'
		);

		$unresolved = array();

		foreach ( array_values( $spellings ) as $index => $transform ) {
			$spelled = call_user_func( $transform, $names[ $index ] );

			wp_autoload_class( $spelled );

			if ( ! self::is_symbol_declared( $names[ $index ] ) ) {
				$unresolved[] = $spelled;
			}
		}

		$this->assertSame(
			array(),
			$unresolved,
			'Every spelling of a mapped name must reach the file it is mapped to.'
		);
	}

	/**
	 * Tests that a name PHP cannot resolve is left alone.
	 *
	 * PHP removes the one leading separator a fully qualified reference is
	 * written with before calling an autoloader, so a name that still starts with
	 * a separator when the handler sees it came from a direct spl_autoload_call()
	 * and names nothing PHP can match. Stripping a run of separators would make
	 * the handler load a file for a name that stays unresolvable, and then load
	 * it a second time when the caller fell through from class_exists() to
	 * interface_exists().
	 */
	public function test_lookup_ignores_a_name_with_a_doubled_leading_separator() {
		$class_map = self::get_class_map();
		$names     = self::get_loadable_class_map_names( $class_map, 1 );

		$this->assertCount( 1, $names, 'The class map must offer an undeclared name to test with.' );

		$files_before = count( get_included_files() );

		wp_autoload_class( '\\\\' . $names[0] );

		$this->assertSame(
			$files_before,
			count( get_included_files() ),
			'A name with a doubled leading separator must not load a file.'
		);

		$this->assertFalse(
			self::is_symbol_declared( $names[0] ),
			'A name with a doubled leading separator must not declare the underlying class.'
		);

		/*
		 * Repeat the call the way a caller falling through from class_exists() to
		 * interface_exists() would. Nothing may be loaded, and in particular the
		 * second pass may not raise a redeclaration error.
		 */
		wp_autoload_class( '\\\\' . $names[0] );

		$this->assertSame(
			$files_before,
			count( get_included_files() ),
			'Repeating the call must stay a no-op.'
		);

		// The same name written the way PHP writes it must still resolve.
		$this->assertTrue(
			self::symbol_resolves( $names[0] ),
			'Ignoring an unresolvable spelling must not stop the resolvable one from working.'
		);
	}

	/**
	 * Tests that no mapped file runs anything at its own file scope.
	 *
	 * This is the property that makes a mapped file safe to load from an
	 * autoloader. A file that requires its own subclasses at file scope recurses
	 * through the autoloader while its parent is still being declared, which
	 * exhausts the stack rather than raising an error; a file that reports a
	 * deprecation emits output in the middle of an unrelated request; and a file
	 * that calls a function assumes a bootstrap state the autoloader cannot
	 * promise, because it runs at the first reference rather than at a fixed
	 * point in the load order.
	 */
	public function test_class_map_entries_have_no_file_scope_side_effects() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$side_effects = array();

		foreach ( $class_map as $class_name => $path ) {
			if ( ! is_string( $path ) || ! is_readable( ABSPATH . $path ) ) {
				// Reported by test_class_map_entry_points_to_a_readable_file().
				continue;
			}

			$side_effect = self::get_file_scope_side_effect( ABSPATH . $path );

			if ( null !== $side_effect ) {
				$side_effects[] = $class_name . ' => ' . $path . ': ' . $side_effect;
			}
		}

		$this->assertSame(
			array(),
			$side_effects,
			'No mapped file may run anything at its own file scope.'
		);
	}

	/**
	 * Tests that the committed class map is what the generator produces.
	 *
	 * The map is a build artifact, so a hand edit or a source change made without
	 * rebuilding would leave it describing a tree that no longer exists. Because
	 * the generator is what enforces every eligibility rule, agreeing with it is
	 * also what keeps an ineligible file from being mapped by hand.
	 */
	public function test_class_map_matches_the_generator() {
		$generator = dirname( untrailingslashit( ABSPATH ) ) . '/tools/build/generate-autoload-classmap.php';

		$this->assertTrue(
			is_readable( $generator ),
			'The class map generator must be present at tools/build/generate-autoload-classmap.php.'
		);

		require_once $generator;

		$generated = wp_autoload_classmap_build( ABSPATH );

		$this->assertSame(
			$generated['map'],
			self::get_class_map(),
			'The committed class map must match the output of build:autoload-classmap. Run `grunt build:autoload-classmap`.'
		);
	}

	/**
	 * Tests that registering the handler again changes nothing.
	 *
	 * wp-includes/autoload.php is required with `require_once` from the bootstrap
	 * and again from this test file, and a plugin may require it as well. PHP
	 * ignores a repeated registration of the same named function, so the handler
	 * has to appear on the autoload stack exactly once however often it is
	 * registered, and resolution has to keep working afterwards.
	 */
	public function test_repeated_registration_is_harmless() {
		$occurrences = static function () {
			$found = 0;

			foreach ( (array) spl_autoload_functions() as $callable ) {
				if ( 'wp_autoload_class' === $callable ) {
					++$found;
				}
			}

			return $found;
		};

		$this->assertSame( 1, $occurrences(), 'The handler must be registered exactly once.' );

		spl_autoload_register( 'wp_autoload_class' );

		$this->assertSame( 1, $occurrences(), 'Registering the handler again must not add a second entry.' );

		$names = self::get_loadable_class_map_names( self::get_class_map(), 1 );

		$this->assertCount( 1, $names, 'The class map must offer an undeclared name to test with.' );

		$this->assertTrue(
			self::symbol_resolves( $names[0] ),
			'A mapped name must still resolve after a repeated registration.'
		);
	}

	/**
	 * Tests that an absent or unusable class map degrades to doing nothing.
	 *
	 * The map is read from a hard-coded path behind a file_exists() guard and its
	 * return value is only trusted when it is an array, so a tree without the
	 * generated map, or with a map that returns something else, has to resolve no
	 * name rather than raise an error. The map is memoized in the handler for the
	 * life of the request, so each case runs in its own process.
	 *
	 * @dataProvider data_unusable_class_maps
	 *
	 * @param string|null $contents Contents to write as the class map, or null to write no map at all.
	 */
	public function test_unusable_class_map_is_tolerated( $contents ) {
		$root = get_temp_dir() . 'wp-autoload-' . md5( __METHOD__ . serialize( $contents ) ) . '/';

		$this->assertTrue(
			wp_mkdir_p( $root . 'wp-includes' ),
			'The temporary tree for the test must be creatable.'
		);

		copy( ABSPATH . WPINC . '/autoload.php', $root . 'wp-includes/autoload.php' );

		if ( null !== $contents ) {
			file_put_contents( $root . 'wp-includes/autoload-classmap.php', $contents );
		}

		$script = sprintf(
			'define( "ABSPATH", %s ); define( "WPINC", "wp-includes" );'
				. ' require ABSPATH . WPINC . "/autoload.php";'
				. ' $found = class_exists( "WP_Query" ) || interface_exists( "WP_Query" );'
				. ' echo $found ? "resolved" : "unresolved";',
			var_export( $root, true )
		);

		$output    = array();
		$exit_code = 0;

		exec( escapeshellarg( PHP_BINARY ) . ' -d error_reporting=E_ALL -d display_errors=1 -r ' . escapeshellarg( $script ) . ' 2>&1', $output, $exit_code );

		// rmdir() only removes an empty directory, so the files have to go first.
		$this->rmdir( untrailingslashit( $root ) );
		$this->delete_folders( untrailingslashit( $root ) );

		$this->assertSame(
			0,
			$exit_code,
			'An unusable class map must not make the autoloader fail: ' . implode( "\n", $output )
		);

		$this->assertSame(
			array( 'unresolved' ),
			$output,
			'An unusable class map must resolve no name, silently.'
		);
	}

	/**
	 * Data provider for the unusable class map cases.
	 *
	 * @return array[] Array of test cases, each holding the contents to write, or null for no file.
	 */
	public function data_unusable_class_maps() {
		return array(
			'no class map at all'         => array( null ),
			'a map that returns nothing'  => array( "<?php\n" ),
			'a map that returns a string' => array( "<?php\nreturn 'not a map';\n" ),
			'a map that returns null'     => array( "<?php\nreturn null;\n" ),
			'an empty map'                => array( "<?php\nreturn array();\n" ),
		);
	}

	/**
	 * Tests that every mapped name is the single symbol its file declares.
	 *
	 * The map is inspected with the tokenizer rather than by loading each file,
	 * so that a side effect of a mapped file, such as the deprecation notice a
	 * deprecated shim reports when it is loaded, cannot influence the result.
	 */
	public function test_class_map_entries_declare_the_mapped_symbol() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$problems = array();

		foreach ( $class_map as $class_name => $path ) {
			if ( ! is_string( $class_name ) || ! is_string( $path ) || ! is_readable( ABSPATH . $path ) ) {
				// Reported by test_class_map_entry_points_to_a_readable_file().
				continue;
			}

			$declared = self::get_declared_symbol_names( ABSPATH . $path );

			if ( 1 !== count( $declared ) ) {
				$problems[] = sprintf(
					'%s: mapped file declares %d symbols (%s)',
					$class_name,
					count( $declared ),
					implode( ', ', $declared )
				);
				continue;
			}

			if ( ! self::names_match( $declared[0], $class_name ) ) {
				$problems[] = sprintf( '%s: mapped file declares %s', $class_name, $declared[0] );
			}
		}

		$this->assertSame(
			array(),
			$problems,
			'Every class map name must match the single class, interface or trait that its file declares.'
		);
	}

	/**
	 * Tests that every generated class map name is already ASCII lower cased.
	 *
	 * PHP resolves class, interface and trait names case insensitively, so the
	 * map is keyed by the ASCII lower cased name and the autoloader lower cases
	 * the requested name before looking it up. A key that is not lower cased is
	 * therefore unreachable: no request can ever produce it.
	 */
	public function test_class_map_names_are_ascii_lower_cased() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$problems = array();

		foreach ( array_keys( $class_map ) as $class_name ) {
			if ( ! is_string( $class_name ) ) {
				// Reported by test_class_map_entry_points_to_a_readable_file().
				continue;
			}

			if ( self::normalize_name( $class_name ) !== $class_name ) {
				$problems[] = $class_name;
			}
		}

		$this->assertSame(
			array(),
			$problems,
			'Every class map name must be ASCII lower cased, otherwise the autoloader can never look it up.'
		);
	}

	/**
	 * Tests that every generated class map name carries a prefix the autoloader prefilters on.
	 *
	 * The autoloader returns before reading the map for any name that cannot
	 * belong to core, which it decides from a short list of prefixes. The list
	 * is read out of the autoloader itself rather than repeated here, so that
	 * the generated map and the prefilter cannot drift apart: a mapped name
	 * outside the list would be silently unreachable in production.
	 */
	public function test_class_map_names_carry_a_prefix_the_autoloader_prefilters_on() {
		$class_map = self::get_class_map();
		$prefixes  = self::get_autoloader_core_prefixes();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );
		$this->assertNotEmpty(
			$prefixes,
			'The core prefix list must be readable from the $core_prefixes declaration in wp-includes/autoload.php.'
		);

		$problems = array();

		foreach ( array_keys( $class_map ) as $class_name ) {
			if ( ! is_string( $class_name ) ) {
				// Reported by test_class_map_entry_points_to_a_readable_file().
				continue;
			}

			if ( ! self::matches_a_core_prefix( $class_name, $prefixes ) ) {
				$problems[] = $class_name;
			}
		}

		$this->assertSame(
			array(),
			$problems,
			sprintf(
				'Every class map name must start with one of the prefixes the autoloader prefilters on (%s).',
				implode( ', ', $prefixes )
			)
		);
	}

	/**
	 * Tests that a name outside the core prefixes is ignored without error.
	 *
	 * A name the autoloader cannot serve has to return silently, so that the
	 * other registered autoloaders still get their turn, and it has to return
	 * before the class map is read, which
	 * test_class_map_is_not_read_before_a_core_name_misses() proves in a process
	 * where the map has not been read yet.
	 */
	public function test_name_outside_the_core_prefixes_is_ignored_without_error() {
		$class_name = self::get_non_core_probe_name();

		$this->assertFalse(
			self::matches_a_core_prefix( self::normalize_name( $class_name ), self::get_autoloader_core_prefixes() ),
			'The name used to test the prefilter must not carry a prefix the autoloader recognizes.'
		);

		$this->assertArrayNotHasKey(
			self::normalize_name( $class_name ),
			self::get_class_map(),
			'The name used to test the prefilter must not be mapped.'
		);

		$files_before = count( get_included_files() );

		// Call the handler directly, so the silent return is proven for the handler itself.
		wp_autoload_class( $class_name );

		$this->assertSame(
			$files_before,
			count( get_included_files() ),
			'A name outside the core prefixes must not load a file.'
		);

		$this->assertFalse(
			self::is_symbol_declared( $class_name ),
			'A name outside the core prefixes must not be declared.'
		);

		// Repeat through the SPL stack, which is how the handler runs in production.
		$this->assertFalse(
			self::symbol_resolves( $class_name ),
			'A name outside the core prefixes must stay unresolvable once every autoloader has had its turn.'
		);
	}

	/**
	 * Tests that a mapped symbol resolves from a reference written in any case.
	 *
	 * PHP matches class, interface and trait names case insensitively, so
	 * `new wp_error()` and `new WP_Error()` are the same reference and both
	 * reach the autoloader with the name exactly as it was written. A case
	 * sensitive lookup would resolve only one of them and leave the other
	 * fatal, so each fixture below is requested in a different case.
	 *
	 * The probe runs in a fresh process because this one has already declared
	 * most mapped symbols during bootstrap, which would let a case sensitive
	 * lookup pass on PHP's own symbol table instead of on the autoloader.
	 */
	public function test_mapped_names_resolve_from_a_reference_in_any_case() {
		$class_map = self::get_class_map();
		$report    = $this->get_isolated_autoloader_probe_report();
		$fixtures  = self::get_case_probe_fixture();

		/*
		 * The handler loads a file, so it cannot treat the three symbol kinds
		 * differently, but the fixture still has to exercise every kind the map
		 * actually contains. The fixture kinds are compared with the kinds
		 * present in the map, so mapping an additional kind fails here until the
		 * fixture covers it.
		 */
		$covered_kinds = array();

		foreach ( $fixtures as $fixture ) {
			$covered_kinds[ $fixture['kind'] ] = true;
		}

		$covered_kinds = array_keys( $covered_kinds );

		sort( $covered_kinds );

		$this->assertSame(
			array(),
			array_values( array_diff( self::get_class_map_symbol_kinds(), $covered_kinds ) ),
			'Every symbol kind the class map contains has to be requested in an alternate case. Add the missing kind to get_case_probe_fixture().'
		);

		foreach ( $fixtures as $fixture ) {
			/*
			 * Matched without regard to case, so that this precondition holds
			 * however the map happens to be keyed and the assertions below stay
			 * the ones that report a case sensitive lookup.
			 */
			$mapped = false;

			foreach ( array_keys( $class_map ) as $mapped_name ) {
				if ( is_string( $mapped_name ) && self::names_match( $fixture['canonical'], $mapped_name ) ) {
					$mapped = true;
					break;
				}
			}

			$this->assertTrue(
				$mapped,
				sprintf(
					'%s has to be mapped for this test to prove anything. Update get_case_probe_fixture() if the symbol was renamed or is no longer autoloaded.',
					$fixture['canonical']
				)
			);

			$this->assertArrayHasKey(
				$fixture['requested'],
				$report['probes'],
				sprintf( 'The probe must report on the reference written as %s.', $fixture['requested'] )
			);

			$this->assertTrue(
				$report['probes'][ $fixture['requested'] ]['resolved'],
				sprintf(
					'A reference written as %s must resolve %s through the autoloader.',
					$fixture['requested'],
					$fixture['canonical']
				)
			);

			$this->assertTrue(
				$report['probes'][ $fixture['requested'] ]['canonical_declared'],
				sprintf(
					'Resolving the reference written as %s must declare %s under its canonical name.',
					$fixture['requested'],
					$fixture['canonical']
				)
			);
		}
	}

	/**
	 * Tests that the class map is not read until a name that could belong to core misses.
	 *
	 * Requiring wp-includes/autoload.php registers the handler without reading
	 * the map, and a name that matches none of the core prefixes returns before
	 * the read as well. This has to be proven in a fresh process, because the map
	 * has already been read by the time this suite runs.
	 */
	public function test_class_map_is_not_read_before_a_core_name_misses() {
		$report = $this->get_isolated_autoloader_probe_report();

		$this->assertTrue(
			$report['handler_registered'],
			'Requiring wp-includes/autoload.php must register the handler with the SPL stack.'
		);

		$this->assertFalse(
			$report['map_read_on_require'],
			'Requiring wp-includes/autoload.php must not read the class map.'
		);

		$this->assertFalse(
			$report['map_read_after_non_core_miss'],
			'A miss on a name outside the core prefixes must not read the class map.'
		);

		$this->assertTrue(
			$report['map_read_after_core_hit'],
			'A mapped name must read the class map, otherwise the probe cannot detect a premature read.'
		);
	}

	/**
	 * Tests that resolving any mapped name on its own never ends in a fatal error.
	 *
	 * Being named for one symbol is not the same as being loadable on demand. A
	 * declaration can reach for a parent that nothing has declared yet, and asking
	 * for such a name raises a fatal error instead of answering, so a name of that
	 * shape must stay out of the map. Two shapes of the problem exist in core and
	 * the generator withdraws both:
	 *
	 * - A file whose declaration inherits from a library core only loads at the
	 *   point of use, such as SimplePie, PHPMailer, IXR or Text_Diff. Reached any
	 *   earlier, the parent is not there to extend.
	 * - A subclass belonging to a family whose base file requires its own
	 *   subclasses at the foot of the file. Asking for the base is safe, because it
	 *   is declared before those requires run, but entering at a subclass leaves
	 *   that file mid compilation, so the require_once that would bring it back is
	 *   skipped as already in progress and the next sibling compiles against a
	 *   parent that does not exist yet.
	 *
	 * The generator decides both from the source alone, so this test is what holds
	 * the property: it asks for every mapped name for real, which is why loosening
	 * either rule fails here.
	 *
	 * Each name is resolved in a process of its own, so one name cannot be
	 * satisfied by a file some earlier name happened to load. A name that resolves
	 * to nothing is not a failure; only a fatal error is.
	 */
	public function test_no_mapped_name_ends_in_a_fatal_error_when_resolved_alone() {
		$names = array_keys( self::get_class_map() );

		$this->assertNotEmpty(
			$names,
			'The class map must contain names, otherwise this test proves nothing.'
		);

		/*
		 * One process per name, rather than one process resolving all of them.
		 * Resolving a name declares whatever its file drags in with it, and several
		 * core families arrive together, so a name asked for after a relative has
		 * already brought it into the process would answer from memory and never
		 * reach the autoloader. Each name therefore gets a process that has
		 * resolved nothing else, which is the only arrangement in which every name
		 * is actually tested.
		 */
		$probe_file = $this->write_isolated_resolution_probe();
		$failures   = array();

		foreach ( $names as $name ) {
			$output = $this->run_isolated_resolution_probe( $probe_file, $name );

			if ( false === strpos( $output, '--WP-AUTOLOAD-RESOLUTION--' ) ) {
				$failures[ $name ] = trim( $output );
			}
		}

		unlink( $probe_file );

		$reports = array();

		foreach ( $failures as $name => $report ) {
			$reports[] = $name . ":\n" . $report;
		}

		$this->assertSame(
			array(),
			$failures,
			'Resolving a mapped name must not raise a fatal error. Before the class map existed these names were '
				. "not autoloadable at all, so a reference to one answered false instead of ending the request:\n"
				. implode( "\n\n", $reports )
		);
	}

	/**
	 * Tests that an unmapped name is ignored whatever case it is spelled in.
	 *
	 * Looking the map up by the lower cased name must widen only what resolves,
	 * never what the autoloader is willing to load: a name that is absent from
	 * the map has to stay a silent miss in every spelling, so that the rest of
	 * the SPL stack still gets its turn.
	 */
	public function test_an_unmapped_noncanonical_name_is_ignored_without_error() {
		$class_map = self::get_class_map();
		$base      = 'WP_Nonexistent_Class_' . md5( __METHOD__ );

		// Carries a core prefix on purpose, so the prefilter does not answer for the map.
		$spellings  = array( strtolower( $base ), strtoupper( $base ), $base );
		$unresolved = array();

		foreach ( $spellings as $spelling ) {
			$this->assertArrayNotHasKey(
				self::normalize_name( $spelling ),
				$class_map,
				"The name used to test a class map miss must not be mapped in any case: {$spelling}."
			);

			$files_before = count( get_included_files() );

			// Call the handler directly, so the silent miss is proven for the handler itself.
			wp_autoload_class( $spelling );

			$this->assertSame(
				$files_before,
				count( get_included_files() ),
				"A class map miss must not load a file: {$spelling}."
			);

			if ( self::symbol_resolves( $spelling ) ) {
				$unresolved[] = $spelling;
			}
		}

		$this->assertSame(
			array(),
			$unresolved,
			'An unmapped name must stay unresolvable in every spelling once every autoloader has had its turn.'
		);
	}

	/**
	 * Tests that nothing in the shipped tree can redeclare a mapped symbol.
	 *
	 * A mapped file is reached through the autoloader, and a plain `require` or
	 * `include` of that same file afterwards recompiles it and ends the request
	 * with "Cannot redeclare". The hazard is not confined to the bootstrap, which
	 * the generator already withdraws from the map: a drop-in, a must-use plugin
	 * or a `class_exists()` probe can resolve a mapped name before any of core's
	 * own includes have run, so the whole shipped tree is inspected. It is
	 * tokenized rather than loaded, so that this test reports a collision instead
	 * of dying on the fatal error it guards against.
	 *
	 * Two include shapes cannot redeclare anything and are therefore allowed:
	 *
	 * - `require_once` and `include_once`, which are a no-op once the autoloader
	 *   has compiled the file, and which declare the symbol themselves when it
	 *   has not.
	 * - A plain `require` or `include` guarded by `class_exists( 'Name', false )`,
	 *   or the interface or trait equivalent, in its own condition. The second
	 *   argument suppresses autoloading, so the guard is true exactly when the
	 *   symbol is already declared and the include is skipped.
	 *
	 * An entry point that never loads wp-settings.php is allowed as well, because
	 * wp-includes/autoload.php is never registered in its process. That claim is
	 * verified rather than assumed by
	 * test_the_exempt_entry_points_never_reach_the_autoloader().
	 */
	public function test_no_mapped_file_can_be_redeclared_by_the_shipped_tree() {
		$class_map = self::get_class_map();

		$this->assertNotEmpty( $class_map, 'The generated class map must not be empty.' );

		$includes   = self::get_shipped_include_targets();
		$exempt     = array_fill_keys( self::get_shipped_files_without_the_autoloader(), true );
		$collisions = array();

		foreach ( $class_map as $class_name => $path ) {
			if ( ! is_string( $class_name ) || ! is_string( $path ) ) {
				// Reported by test_class_map_entry_points_to_a_readable_file().
				continue;
			}

			if ( ! isset( $includes[ $path ] ) ) {
				continue;
			}

			foreach ( $includes[ $path ] as $include ) {
				if ( $include['once'] || $include['guarded'] || isset( $exempt[ $include['file'] ] ) ) {
					continue;
				}

				$collisions[] = sprintf(
					'%1$s => %2$s, reached by an unguarded %3$s in %4$s on line %5$d',
					$class_name,
					$path,
					$include['form'],
					$include['file'],
					$include['line']
				);
			}
		}

		$this->assertSame(
			array(),
			$collisions,
			'A mapped file may only be included where the include cannot redeclare its symbol: '
				. 'use require_once, or guard a plain require with class_exists( ..., false ).'
		);
	}

	/**
	 * Tests that the entry points exempted above really run without the autoloader.
	 *
	 * The exemption in test_no_mapped_file_can_be_redeclared_by_the_shipped_tree()
	 * rests entirely on those files bootstrapping themselves rather than through
	 * wp-settings.php. Should one of them ever load the bootstrap, or the
	 * autoloader directly, its unguarded includes would become able to redeclare
	 * a mapped symbol and the exemption would have to go, so the property is
	 * asserted here rather than trusted.
	 */
	public function test_the_exempt_entry_points_never_reach_the_autoloader() {
		$problems = array();

		foreach ( self::get_shipped_files_without_the_autoloader() as $relative ) {
			$file = ABSPATH . $relative;

			if ( ! is_readable( $file ) ) {
				$problems[] = $relative . ': not readable.';
				continue;
			}

			$source = file_get_contents( $file );

			if ( ! is_string( $source ) ) {
				$problems[] = $relative . ': could not be read.';
				continue;
			}

			// Bootstraps itself, which is what makes it an entry point rather than an include.
			if ( false === strpos( $source, "define( 'WPINC'" ) ) {
				$problems[] = $relative . ': does not define WPINC for itself.';
			}

			foreach ( array( 'wp-settings.php', 'wp-load.php', 'autoload.php' ) as $bootstrap ) {
				if ( false !== strpos( $source, $bootstrap ) ) {
					$problems[] = $relative . ': names ' . $bootstrap . ', so it may reach the autoloader.';
				}
			}
		}

		$this->assertSame(
			array(),
			$problems,
			'An entry point exempted from the redeclaration check must bootstrap itself and never reach wp-includes/autoload.php.'
		);
	}

	/**
	 * Returns the generated class map that wp_autoload_class() resolves against.
	 *
	 * Consumes the generated manifest the way core does elsewhere: a PHP file
	 * that returns an array, read with an assigned require behind a
	 * file_exists() guard and memoized for the rest of the run. The locator
	 * matches the one the autoloader uses, so both read the same file whether
	 * the tests run against the development tree or a built tree.
	 *
	 * @return array Map of class, interface and trait names to paths relative to
	 *               ABSPATH, or an empty array when the map is missing or does
	 *               not return an array.
	 */
	private static function get_class_map() {
		static $class_map = null;

		if ( null === $class_map ) {
			$class_map      = array();
			$class_map_file = ABSPATH . WPINC . '/autoload-classmap.php';

			if ( file_exists( $class_map_file ) ) {
				$map = require $class_map_file;

				if ( is_array( $map ) ) {
					$class_map = $map;
				}
			}
		}

		return $class_map;
	}

	/**
	 * Returns the first mapped name that is not declared yet and is safe to load.
	 *
	 * @param array $class_map The generated class map.
	 * @return string|null A mapped name that can be loaded, or null when every
	 *                     mapped name is already declared or has to be skipped.
	 */
	private static function get_loadable_class_map_name( $class_map ) {
		$names = self::get_loadable_class_map_names( $class_map, 1 );

		return $names ? $names[0] : null;
	}

	/**
	 * Returns up to a given number of mapped names that are not declared yet.
	 *
	 * Used by the tests that have to prove the handler actually ran: a name that
	 * is already declared would report success without the autoloader being
	 * consulted at all.
	 *
	 * @param array $class_map The generated class map.
	 * @param int   $count     How many names to return.
	 * @return string[] Mapped names that can be loaded, at most $count of them.
	 */
	private static function get_loadable_class_map_names( $class_map, $count ) {
		$names = array();

		foreach ( $class_map as $class_name => $path ) {
			if ( count( $names ) >= $count ) {
				break;
			}

			if ( ! is_string( $class_name ) || ! is_string( $path ) ) {
				continue;
			}

			if ( self::is_symbol_declared( $class_name ) ) {
				continue;
			}

			if ( self::may_report_deprecation_on_load( ABSPATH . $path ) ) {
				continue;
			}

			$names[] = $class_name;
		}

		return $names;
	}

	/**
	 * Returns a name with the case of every other letter flipped.
	 *
	 * @param string $name Name to respell.
	 * @return string The respelled name.
	 */
	private static function alternate_case( $name ) {
		$respelled = '';

		for ( $index = 0, $length = strlen( $name ); $index < $length; $index++ ) {
			$respelled .= 0 === $index % 2 ? strtoupper( $name[ $index ] ) : strtolower( $name[ $index ] );
		}

		return $respelled;
	}

	/**
	 * Returns a name written with one leading namespace separator.
	 *
	 * @param string $name Name to qualify.
	 * @return string The qualified name.
	 */
	private static function prefix_separator( $name ) {
		return '\\' . $name;
	}

	/**
	 * Returns a description of the first statement a file runs at its own file scope.
	 *
	 * The file is tokenized rather than loaded, so inspecting it cannot trigger
	 * the very side effect being looked for. Only a declaration, a namespace, an
	 * import, a `declare` and an attribute are inert at the top level; anything
	 * else, from a `require` through an `if` to a bare function call, executes.
	 *
	 * Written independently of the generator on purpose: two implementations that
	 * agree is a stronger guarantee than one implementation checking itself.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return string|null A description of the first executing statement, or null when there is none.
	 */
	private static function get_file_scope_side_effect( $file ) {
		$source = file_get_contents( $file );

		if ( ! is_string( $source ) ) {
			return 'the file could not be read';
		}

		$tokens = token_get_all( $source );

		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT, T_OPEN_TAG, T_CLOSE_TAG );
		$inert     = array( T_NAMESPACE, T_USE, T_DECLARE );
		$modifiers = array( T_ABSTRACT, T_FINAL );
		$declaring = array( T_CLASS, T_INTERFACE, T_TRAIT );

		if ( defined( 'T_ENUM' ) ) {
			$declaring[] = T_ENUM;
		}

		if ( defined( 'T_READONLY' ) ) {
			$modifiers[] = T_READONLY;
		}

		for ( $index = 0; $index < $total; $index++ ) {
			$token = $tokens[ $index ];

			if ( is_string( $token ) ) {
				if ( ';' === $token ) {
					continue;
				}

				return sprintf( '%s at the top level', $token );
			}

			if ( in_array( $token[0], $ignorable, true ) || in_array( $token[0], $modifiers, true ) ) {
				continue;
			}

			// An attribute annotates the declaration that follows it and runs nothing.
			if ( defined( 'T_ATTRIBUTE' ) && T_ATTRIBUTE === $token[0] ) {
				$index = self::skip_attribute( $tokens, $index ) - 1;
				continue;
			}

			// A namespace, an import and a `declare` end at their semicolon.
			if ( in_array( $token[0], $inert, true ) ) {
				for ( ++$index; $index < $total; $index++ ) {
					if ( is_string( $tokens[ $index ] ) && ';' === $tokens[ $index ] ) {
						break;
					}

					if ( is_string( $tokens[ $index ] ) && '{' === $tokens[ $index ] ) {
						return sprintf( '%s with a body at the top level', token_name( $token[0] ) );
					}
				}

				continue;
			}

			if ( in_array( $token[0], $declaring, true ) ) {
				$body = self::skip_declaration( $tokens, $index );

				if ( null === $body ) {
					return sprintf( 'an anonymous or malformed %s', strtolower( token_name( $token[0] ) ) );
				}

				$index = $body - 1;
				continue;
			}

			return sprintf( '%s on line %d', token_name( $token[0] ), $token[2] );
		}

		return null;
	}

	/**
	 * Returns the index of the first token after an attribute.
	 *
	 * @param array $tokens Token list from token_get_all().
	 * @param int   $index  Index of the T_ATTRIBUTE token.
	 * @return int Index of the first token after the attribute.
	 */
	private static function skip_attribute( $tokens, $index ) {
		$total = count( $tokens );
		$depth = 0;

		for ( ; $index < $total; $index++ ) {
			if ( is_array( $tokens[ $index ] ) ) {
				if ( defined( 'T_ATTRIBUTE' ) && T_ATTRIBUTE === $tokens[ $index ][0] ) {
					++$depth;
				}

				continue;
			}

			if ( '[' === $tokens[ $index ] ) {
				++$depth;
				continue;
			}

			if ( ']' === $tokens[ $index ] ) {
				--$depth;

				if ( 0 === $depth ) {
					return $index + 1;
				}
			}
		}

		return $total;
	}

	/**
	 * Returns the index of the first token after a declaration body.
	 *
	 * @param array $tokens Token list from token_get_all().
	 * @param int   $index  Index of the declaring keyword.
	 * @return int|null Index of the first token after the body, or null when the declaration is anonymous.
	 */
	private static function skip_declaration( $tokens, $index ) {
		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT );
		$cursor    = $index + 1;

		while ( $cursor < $total && is_array( $tokens[ $cursor ] ) && in_array( $tokens[ $cursor ][0], $ignorable, true ) ) {
			++$cursor;
		}

		if ( $cursor >= $total || ! is_array( $tokens[ $cursor ] ) || T_STRING !== $tokens[ $cursor ][0] ) {
			return null;
		}

		$depth = 0;

		for ( ; $cursor < $total; $cursor++ ) {
			if ( is_array( $tokens[ $cursor ] ) ) {
				if ( T_CURLY_OPEN === $tokens[ $cursor ][0]
					|| ( defined( 'T_DOLLAR_OPEN_CURLY_BRACES' ) && T_DOLLAR_OPEN_CURLY_BRACES === $tokens[ $cursor ][0] )
				) {
					++$depth;
				}

				continue;
			}

			if ( '{' === $tokens[ $cursor ] ) {
				++$depth;
				continue;
			}

			if ( '}' === $tokens[ $cursor ] ) {
				--$depth;

				if ( 0 === $depth ) {
					return $cursor + 1;
				}
			}
		}

		return $total;
	}

	/**
	 * Determines whether loading a file may report a deprecation.
	 *
	 * Conservatively skips files that reference a deprecation helper, because a
	 * deprecation raised while a file is being loaded is converted into an
	 * exception by the test configuration and belongs to the loaded file rather
	 * than to the autoloader.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return bool Whether the file has to be skipped.
	 */
	private static function may_report_deprecation_on_load( $file ) {
		if ( ! is_readable( $file ) ) {
			return true;
		}

		$source = file_get_contents( $file );
		$calls  = array(
			'_deprecated_file(',
			'_deprecated_class(',
			'_deprecated_function(',
			'trigger_error(',
		);

		foreach ( $calls as $call ) {
			if ( false !== strpos( $source, $call ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Returns the names of every class, interface and trait declared so far.
	 *
	 * @return string[] Declared symbol names.
	 */
	private static function get_declared_symbols() {
		return array_merge( get_declared_classes(), get_declared_interfaces(), get_declared_traits() );
	}

	/**
	 * Determines whether a name is already declared, without triggering autoloading.
	 *
	 * The class map holds interfaces as well as classes, and spl_autoload_register()
	 * resolves interfaces and traits too, so all three symbol tables are checked.
	 *
	 * @param string $class_name Name to look for.
	 * @return bool Whether the name is declared.
	 */
	private static function is_symbol_declared( $class_name ) {
		return class_exists( $class_name, false )
			|| interface_exists( $class_name, false )
			|| trait_exists( $class_name, false );
	}

	/**
	 * Determines whether a name resolves, letting the registered autoloaders run.
	 *
	 * @param string $class_name Name to resolve.
	 * @return bool Whether the name resolves.
	 */
	private static function symbol_resolves( $class_name ) {
		return class_exists( $class_name )
			|| interface_exists( $class_name )
			|| trait_exists( $class_name );
	}

	/**
	 * Determines whether a symbol is the target itself or one of its relatives.
	 *
	 * A relative is a parent class or interface, an implemented interface or a
	 * used trait: all of them are resolved while the target is being compiled,
	 * so declaring them is an expected consequence of loading the target.
	 *
	 * @param string $symbol      Newly declared symbol name.
	 * @param string $target_name Name whose relatives are expected.
	 * @return bool Whether the symbol is expected.
	 */
	private static function is_related_symbol( $symbol, $target_name ) {
		if ( self::names_match( $symbol, $target_name ) ) {
			return true;
		}

		$relatives = array();

		foreach ( array( 'class_parents', 'class_implements', 'class_uses' ) as $relation ) {
			$found = $relation( $target_name, false );

			if ( is_array( $found ) ) {
				$relatives = array_merge( $relatives, array_keys( $found ) );
			}
		}

		foreach ( $relatives as $relative ) {
			if ( self::names_match( $symbol, $relative ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Compares two symbol names the way PHP resolves them.
	 *
	 * PHP matches class, interface and trait names case insensitively. A mapped
	 * name may be namespace qualified while the tokenizer only sees the short
	 * name in the declaration, so a match on the last segment counts too.
	 *
	 * @param string $declared_name Name taken from a declaration.
	 * @param string $mapped_name   Name taken from the class map.
	 * @return bool Whether the two names refer to the same symbol.
	 */
	private static function names_match( $declared_name, $mapped_name ) {
		if ( 0 === strcasecmp( $declared_name, $mapped_name ) ) {
			return true;
		}

		$segments = explode( '\\', $mapped_name );

		return 0 === strcasecmp( $declared_name, end( $segments ) );
	}

	/**
	 * Returns the class, interface and trait names declared in a file.
	 *
	 * The file is tokenized rather than loaded, so inspecting it has no side
	 * effect. A `::class` constant and an anonymous class are expressions rather
	 * than declarations, so neither is counted.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return string[] Declared names, in the order they appear in the file.
	 */
	private static function get_declared_symbol_names( $file ) {
		$names = array();

		foreach ( self::get_declared_symbols_with_kinds( $file ) as $symbol ) {
			$names[] = $symbol['name'];
		}

		return $names;
	}

	/**
	 * Returns the class, interface and trait declarations in a file, with their kind.
	 *
	 * Shares one tokenizer pass with get_declared_symbol_names(), so that both
	 * views of a file agree on what counts as a declaration.
	 *
	 * @param string $file Absolute path of the file to inspect.
	 * @return array[] {
	 *     Declarations, in the order they appear in the file.
	 *
	 *     @type array ...$0 {
	 *         @type string $kind One of 'class', 'interface' or 'trait'.
	 *         @type string $name The declared name.
	 *     }
	 * }
	 */
	private static function get_declared_symbols_with_kinds( $file ) {
		$tokens    = token_get_all( file_get_contents( $file ) );
		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT );
		$kinds     = array(
			T_CLASS     => 'class',
			T_INTERFACE => 'interface',
			T_TRAIT     => 'trait',
		);
		$declaring = array_keys( $kinds );
		$symbols   = array();

		for ( $index = 0; $index < $total; $index++ ) {
			if ( ! is_array( $tokens[ $index ] ) || ! in_array( $tokens[ $index ][0], $declaring, true ) ) {
				continue;
			}

			// `Foo::class` reads the name of a class, it does not declare one.
			$previous = $index - 1;

			while ( $previous >= 0 && is_array( $tokens[ $previous ] ) && in_array( $tokens[ $previous ][0], $ignorable, true ) ) {
				--$previous;
			}

			if ( $previous >= 0 && is_array( $tokens[ $previous ] ) && T_DOUBLE_COLON === $tokens[ $previous ][0] ) {
				continue;
			}

			// A declaration is followed by its name. An anonymous class is not.
			$next = $index + 1;

			while ( $next < $total && is_array( $tokens[ $next ] ) && in_array( $tokens[ $next ][0], $ignorable, true ) ) {
				++$next;
			}

			if ( $next < $total && is_array( $tokens[ $next ] ) && T_STRING === $tokens[ $next ][0] ) {
				$symbols[] = array(
					'kind' => $kinds[ $tokens[ $index ][0] ],
					'name' => $tokens[ $next ][1],
				);
			}
		}

		return $symbols;
	}

	/**
	 * Returns the symbol kinds the generated class map actually contains.
	 *
	 * Read from the mapped files rather than assumed from their names, so that a
	 * trait or an interface entering the map is noticed even if it does not
	 * follow core's `interface-` or `trait-` file naming.
	 *
	 * @return string[] Sorted unique kinds, drawn from 'class', 'interface' and
	 *                  'trait'.
	 */
	private static function get_class_map_symbol_kinds() {
		static $kinds = null;

		if ( null !== $kinds ) {
			return $kinds;
		}

		$kinds = array();

		foreach ( self::get_class_map() as $class_name => $path ) {
			if ( ! is_string( $class_name ) || ! is_string( $path ) || ! is_readable( ABSPATH . $path ) ) {
				// Reported by test_class_map_entry_points_to_a_readable_file().
				continue;
			}

			foreach ( self::get_declared_symbols_with_kinds( ABSPATH . $path ) as $symbol ) {
				$kinds[ $symbol['kind'] ] = true;
			}
		}

		$kinds = array_keys( $kinds );

		sort( $kinds );

		return $kinds;
	}

	/**
	 * Lower cases the ASCII letters of a symbol name.
	 *
	 * Mirrors the normalization the autoloader performs, character for
	 * character. strtr() is used rather than strtolower() for the same reason
	 * the autoloader uses it: strtolower() only stopped depending on the locale
	 * in PHP 8.2, and a Turkish locale folds `I` outside ASCII.
	 *
	 * @param string $name Symbol name.
	 * @return string The name with its ASCII letters lower cased.
	 */
	private static function normalize_name( $name ) {
		return strtr( $name, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz' );
	}

	/**
	 * Determines whether a normalized name starts with one of the given prefixes.
	 *
	 * @param string   $name     Normalized symbol name.
	 * @param string[] $prefixes Normalized prefixes to test against.
	 * @return bool Whether the name starts with one of the prefixes.
	 */
	private static function matches_a_core_prefix( $name, $prefixes ) {
		foreach ( $prefixes as $prefix ) {
			if ( 0 === strncmp( $name, $prefix, strlen( $prefix ) ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Returns the prefixes the autoloader prefilters requested names on.
	 *
	 * Read out of the `$core_prefixes` declaration in the autoloader by
	 * tokenizing it, so the list is never duplicated here. Duplicating it would
	 * let the two copies drift, which is exactly the failure the tests using
	 * this helper exist to catch.
	 *
	 * @return string[] The declared prefixes, or an empty array when the
	 *                  declaration cannot be read.
	 */
	private static function get_autoloader_core_prefixes() {
		static $prefixes = null;

		if ( null !== $prefixes ) {
			return $prefixes;
		}

		$prefixes = array();
		$source   = file_get_contents( ABSPATH . WPINC . '/autoload.php' );

		if ( false === $source ) {
			return $prefixes;
		}

		$tokens    = token_get_all( $source );
		$total     = count( $tokens );
		$ignorable = array( T_WHITESPACE, T_COMMENT, T_DOC_COMMENT );

		for ( $index = 0; $index < $total; $index++ ) {
			if ( ! is_array( $tokens[ $index ] )
				|| T_VARIABLE !== $tokens[ $index ][0]
				|| '$core_prefixes' !== $tokens[ $index ][1]
			) {
				continue;
			}

			$assigned  = false;
			$depth     = 0;
			$collected = array();

			for ( $next = $index + 1; $next < $total; $next++ ) {
				$token = $tokens[ $next ];

				if ( is_array( $token ) ) {
					if ( in_array( $token[0], $ignorable, true ) ) {
						continue;
					}

					if ( $assigned && $depth > 0 && T_CONSTANT_ENCAPSED_STRING === $token[0] ) {
						$collected[] = trim( $token[1], '"\'' );
					}

					// T_ARRAY and anything else in the expression is skipped.
					continue;
				}

				if ( ! $assigned ) {
					if ( '=' === $token ) {
						$assigned = true;
						continue;
					}

					// Not the declaration. Try the next occurrence of the variable.
					break;
				}

				if ( '(' === $token || '[' === $token ) {
					++$depth;
					continue;
				}

				if ( ')' === $token || ']' === $token ) {
					--$depth;

					if ( 0 === $depth ) {
						break;
					}

					continue;
				}

				if ( ';' === $token ) {
					break;
				}
			}

			if ( array() !== $collected ) {
				$prefixes = $collected;
				break;
			}
		}

		return $prefixes;
	}

	/**
	 * Returns a name that no core file can declare and no prefix can match.
	 *
	 * @return string A name outside the core prefixes.
	 */
	private static function get_non_core_probe_name() {
		return 'Vendor_Unmapped_Autoloader_Probe';
	}

	/**
	 * Returns the references the case sensitivity probe resolves.
	 *
	 * Each fixture names a different symbol, so that each case is resolved by
	 * the autoloader rather than by PHP's symbol table answering for a symbol an
	 * earlier fixture already declared. Every mapped file listed here declares
	 * its symbol without extending a parent, implementing an interface or using
	 * a trait, so it can be compiled in a process where nothing else is loaded.
	 *
	 * @return array[] {
	 *     @type array ...$0 {
	 *         @type string $requested The reference to resolve, as written.
	 *         @type string $canonical The name the mapped file declares.
	 *         @type string $kind      Either 'class' or 'interface'.
	 *     }
	 * }
	 */
	private static function get_case_probe_fixture() {
		return array(
			array(
				'requested' => 'wp_http_proxy',
				'canonical' => 'WP_HTTP_Proxy',
				'kind'      => 'class',
			),
			array(
				'requested' => 'WP_LIST_UTIL',
				'canonical' => 'WP_List_Util',
				'kind'      => 'class',
			),
			array(
				'requested' => 'Wp_Token_Map',
				'canonical' => 'WP_Token_Map',
				'kind'      => 'class',
			),
			array(
				'requested' => 'wp_sync_storage',
				'canonical' => 'WP_Sync_Storage',
				'kind'      => 'interface',
			),
		);
	}

	/**
	 * Runs the autoloader in a fresh PHP process and returns what it observed.
	 *
	 * Two of the guarantees under test are only observable before anything else
	 * has loaded: whether the class map has been read yet, and whether a
	 * reference resolves through the autoloader rather than through a symbol the
	 * bootstrap already declared. Both are therefore measured in a process that
	 * requires nothing but the autoloader, spawned with WP_PHP_BINARY so that the
	 * interpreter matches the one running this suite.
	 *
	 * The probe writes its report between sentinels, so that anything else the
	 * process emits stays visible in the failure message instead of corrupting
	 * the report.
	 *
	 * @return array {
	 *     @type bool  $handler_registered           Whether requiring the autoloader registered the handler.
	 *     @type bool  $map_read_on_require          Whether requiring the autoloader read the class map.
	 *     @type bool  $map_read_after_non_core_miss Whether a non-core miss read the class map.
	 *     @type bool  $map_read_after_core_hit      Whether a mapped name read the class map.
	 *     @type array $probes                       Per reference results, keyed by the requested name.
	 * }
	 */
	private function get_isolated_autoloader_probe_report() {
		static $report = null;

		if ( null !== $report ) {
			return $report;
		}

		$probe_file = get_temp_dir() . 'wp-autoload-probe-' . md5( __CLASS__ . ABSPATH ) . '.php';

		$this->assertNotFalse(
			file_put_contents( $probe_file, self::get_isolated_probe_source() ),
			'The autoloader probe must be writable to the temporary directory.'
		);

		$command = sprintf(
			'%s %s %s %s %s 2>&1',
			WP_PHP_BINARY,
			escapeshellarg( $probe_file ),
			escapeshellarg( ABSPATH ),
			escapeshellarg( WPINC ),
			escapeshellarg( wp_json_encode( self::get_case_probe_fixture() ) )
		);

		$output = shell_exec( $command );

		unlink( $probe_file );

		$this->assertIsString(
			$output,
			'The autoloader probe must run in a separate PHP process. Process spawning is required by the test bootstrap itself.'
		);

		$matched = preg_match( '/--WP-AUTOLOAD-PROBE--(.*)--WP-AUTOLOAD-PROBE--/s', $output, $matches );

		$this->assertSame(
			1,
			$matched,
			"The autoloader probe must report between its sentinels. It emitted:\n" . $output
		);

		$decoded = json_decode( $matches[1], true );

		$this->assertIsArray(
			$decoded,
			"The autoloader probe report must be readable JSON. It emitted:\n" . $output
		);

		$report = $decoded;

		return $report;
	}

	/**
	 * Returns the source of the isolated autoloader probe.
	 *
	 * The probe deliberately requires nothing but the autoloader, so that the
	 * only thing that can put the class map into the included file list is the
	 * autoloader itself. It misses on a non-core name before it resolves any
	 * mapped name, because the order is what makes a premature read of the map
	 * detectable.
	 *
	 * @return string The probe source.
	 */
	private static function get_isolated_probe_source() {
		$non_core_name = self::get_non_core_probe_name();

		$source = <<<'PROBE'
<?php
define( 'ABSPATH', $argv[1] );
define( 'WPINC', $argv[2] );

$class_map_file = ABSPATH . WPINC . '/autoload-classmap.php';
$report         = array( 'probes' => array() );

require ABSPATH . WPINC . '/autoload.php';

$report['handler_registered']  = in_array( 'wp_autoload_class', (array) spl_autoload_functions(), true );
$report['map_read_on_require'] = in_array( $class_map_file, get_included_files(), true );

// A name no core file can declare must not make the handler read the map.
class_exists( 'WP_AUTOLOAD_PROBE_NON_CORE_NAME' );

$report['map_read_after_non_core_miss'] = in_array( $class_map_file, get_included_files(), true );

foreach ( json_decode( $argv[3], true ) as $fixture ) {
	$resolved = 'interface' === $fixture['kind']
		? interface_exists( $fixture['requested'] )
		: class_exists( $fixture['requested'] );

	/*
	 * The canonical name is checked without autoloading, so that it reports
	 * whether resolving the reference declared the symbol rather than whether
	 * a second autoload attempt would.
	 */
	$declared = class_exists( $fixture['canonical'], false )
		|| interface_exists( $fixture['canonical'], false )
		|| trait_exists( $fixture['canonical'], false );

	$report['probes'][ $fixture['requested'] ] = array(
		'resolved'           => $resolved,
		'canonical_declared' => $declared,
	);
}

$report['map_read_after_core_hit'] = in_array( $class_map_file, get_included_files(), true );

echo '--WP-AUTOLOAD-PROBE--' . json_encode( $report ) . '--WP-AUTOLOAD-PROBE--';
PROBE;

		return str_replace( 'WP_AUTOLOAD_PROBE_NON_CORE_NAME', $non_core_name, $source );
	}

	/**
	 * Writes the isolated resolution probe and returns its path.
	 *
	 * Written once and reused for every name, because the probe does not vary: only
	 * the name it is asked to resolve does, and that arrives as an argument.
	 *
	 * @return string Path to the probe.
	 */
	private function write_isolated_resolution_probe() {
		$probe_file = get_temp_dir() . 'wp-autoload-resolution-probe-' . md5( __CLASS__ . ABSPATH ) . '.php';

		$this->assertNotFalse(
			file_put_contents( $probe_file, self::get_isolated_resolution_probe_source() ),
			'The resolution probe must be writable to the temporary directory.'
		);

		return $probe_file;
	}

	/**
	 * Resolves one mapped name in a separate process and returns what it emitted.
	 *
	 * Spawned with the same PHP binary the test bootstrap uses for its install
	 * step. Standard error is folded into the output so that the message of a fatal
	 * error survives to be reported, and the whole output is returned rather than a
	 * parsed report because a process that dies has no report to give.
	 *
	 * @param string $probe_file Path to the probe.
	 * @param string $name       The name to resolve.
	 * @return string Everything the process wrote to either stream.
	 */
	private function run_isolated_resolution_probe( $probe_file, $name ) {
		$command = sprintf(
			'%s %s %s %s 2>&1',
			WP_PHP_BINARY,
			escapeshellarg( $probe_file ),
			escapeshellarg( ABSPATH ),
			escapeshellarg( $name )
		);

		$output = shell_exec( $command );

		$this->assertIsString(
			$output,
			'The resolution probe must run in a separate PHP process. Process spawning is required by the test bootstrap itself.'
		);

		return $output;
	}

	/**
	 * Returns the source of the isolated resolution probe.
	 *
	 * Installs what a mapped symbol may depend on, and deliberately nothing else:
	 *
	 * - The two vendored autoloaders, so that a declaration inheriting from one of
	 *   those namespaces resolves rather than reaching an undeclared parent.
	 * - A stub for _deprecated_file(), which core declares in functions.php. Two
	 *   mapped files announce their own deprecation as they load, and without the
	 *   stub they would fail on an undefined function rather than on anything to do
	 *   with the class map.
	 *
	 * The libraries core loads only where they are used are omitted, so a mapped
	 * name that inherits from one of them fails here. The sentinel is emitted only
	 * once the name has been resolved, so its absence is what reports a process that
	 * did not survive resolving it.
	 *
	 * @return string The probe source.
	 */
	private static function get_isolated_resolution_probe_source() {
		return <<<'PROBE'
<?php
define( 'ABSPATH', $argv[1] );
define( 'WPINC', 'wp-includes' );

// Declared by core in wp-includes/functions.php, which this probe does not load.
function _deprecated_file( $file, $version, $replacement = '', $message = '' ) {}

foreach ( array( '/Requests/src/Autoload.php', '/php-ai-client/autoload.php' ) as $vendor_autoloader ) {
	require ABSPATH . WPINC . $vendor_autoloader;
}

WpOrg\Requests\Autoload::register();

require ABSPATH . WPINC . '/autoload.php';

$name     = $argv[2];
$resolved = class_exists( $name ) || interface_exists( $name ) || trait_exists( $name );

echo '--WP-AUTOLOAD-RESOLUTION--' . ( $resolved ? 'resolved' : 'unresolved' ) . "\n";
PROBE;
	}

	/**
	 * Returns the shipped entry points that run without the core autoloader.
	 *
	 * Both define ABSPATH and WPINC for themselves and load the handful of files
	 * they need directly, never wp-settings.php, so wp-includes/autoload.php is
	 * never registered in their process and nothing can have autoloaded the file
	 * they require. That property is asserted by
	 * test_the_exempt_entry_points_never_reach_the_autoloader().
	 *
	 * @return string[] Paths relative to ABSPATH.
	 */
	private static function get_shipped_files_without_the_autoloader() {
		return array(
			'wp-admin/load-scripts.php',
			'wp-admin/load-styles.php',
		);
	}

	/**
	 * Returns every include of a shipped file made anywhere in the shipped tree.
	 *
	 * Each include is described rather than merely counted, because whether it can
	 * redeclare a symbol depends on its form and on the guard in front of it.
	 *
	 * The scan is memoized, so the tree is walked once for the whole class.
	 *
	 * @return array[] Paths of the included files, relative to ABSPATH, each mapped
	 *                 to a list of arrays with the keys 'file', 'line', 'form',
	 *                 'once' and 'guarded'.
	 */
	private static function get_shipped_include_targets() {
		static $targets = null;

		if ( null !== $targets ) {
			return $targets;
		}

		$targets    = array();
		$files      = self::get_shipped_php_files();
		$is_shipped = array_fill_keys( $files, true );

		foreach ( $files as $file ) {
			foreach ( self::get_include_targets( $file, $is_shipped ) as $include ) {
				$path = $include['path'];

				unset( $include['path'] );

				if ( ! isset( $targets[ $path ] ) ) {
					$targets[ $path ] = array();
				}

				$targets[ $path ][] = $include;
			}
		}

		return $targets;
	}

	/**
	 * Returns the PHP files of the shipped tree, relative to ABSPATH.
	 *
	 * The shipped tree is the root level files plus wp-includes and wp-admin,
	 * which is the same surface the generator consults. Everything under
	 * wp-content is bundled content rather than core, so it is left out: a
	 * bundled theme or plugin cannot be held to a core loading invariant.
	 *
	 * @return string[] Sorted forward slashed paths, relative to ABSPATH.
	 */
	private static function get_shipped_php_files() {
		static $files = null;

		if ( null !== $files ) {
			return $files;
		}

		$files = array();

		foreach ( glob( ABSPATH . '*.php' ) as $file ) {
			$files[] = basename( $file );
		}

		foreach ( array( 'wp-includes', 'wp-admin' ) as $directory ) {
			if ( ! is_dir( ABSPATH . $directory ) ) {
				continue;
			}

			$iterator = new RecursiveIteratorIterator(
				new RecursiveDirectoryIterator( ABSPATH . $directory, FilesystemIterator::SKIP_DOTS )
			);

			foreach ( $iterator as $file ) {
				if ( $file->isFile() && 'php' === strtolower( $file->getExtension() ) ) {
					$files[] = str_replace( '\\', '/', substr( $file->getPathname(), strlen( ABSPATH ) ) );
				}
			}
		}

		sort( $files );

		return $files;
	}

	/**
	 * Returns the shipped files a single file includes, described one by one.
	 *
	 * Only literal paths are resolved, which is every include in the shipped tree
	 * that names a file at all. The autoloader's own `require $file;` holds no
	 * literal and is skipped, as is any other computed path: nothing that cannot
	 * be resolved statically is reported, so a collision is only ever claimed on
	 * evidence.
	 *
	 * @param string $file       Path of the including file, relative to ABSPATH.
	 * @param array  $is_shipped Lookup of the shipped paths, keyed by path.
	 * @return array[] One array per include, with the keys 'path', 'file', 'line',
	 *                 'form', 'once' and 'guarded'.
	 */
	private static function get_include_targets( $file, $is_shipped ) {
		$source = file_get_contents( ABSPATH . $file );

		if ( ! is_string( $source ) ) {
			return array();
		}

		// Tokenizing every shipped file is wasteful when most name no include at all.
		if ( false === stripos( $source, 'require' ) && false === stripos( $source, 'include' ) ) {
			return array();
		}

		$tokens    = token_get_all( $source );
		$total     = count( $tokens );
		$including = array(
			T_REQUIRE      => 'require',
			T_REQUIRE_ONCE => 'require_once',
			T_INCLUDE      => 'include',
			T_INCLUDE_ONCE => 'include_once',
		);
		$includes  = array();

		for ( $index = 0; $index < $total; $index++ ) {
			if ( ! is_array( $tokens[ $index ] ) || ! isset( $including[ $tokens[ $index ][0] ] ) ) {
				continue;
			}

			$form = $including[ $tokens[ $index ][0] ];
			$line = $tokens[ $index ][2];

			/*
			 * Read the statement up to its semicolon. The expression is needed
			 * whole, because which directory a literal is relative to depends on
			 * the constants that are concatenated with it.
			 */
			$expression = '';
			$literal    = null;

			for ( $cursor = $index + 1; $cursor < $total; $cursor++ ) {
				if ( ';' === $tokens[ $cursor ] ) {
					break;
				}

				if ( ! is_array( $tokens[ $cursor ] ) ) {
					$expression .= $tokens[ $cursor ];
					continue;
				}

				$expression .= $tokens[ $cursor ][1];

				if ( null !== $literal || T_CONSTANT_ENCAPSED_STRING !== $tokens[ $cursor ][0] ) {
					continue;
				}

				$value = substr( $tokens[ $cursor ][1], 1, -1 );

				if ( '.php' === substr( $value, -4 ) ) {
					$literal = ltrim( $value, '/' );
				}
			}

			if ( null === $literal ) {
				continue;
			}

			$resolved = self::resolve_include_target( $file, $expression, $literal, $is_shipped );

			if ( null === $resolved ) {
				continue;
			}

			$includes[] = array(
				'path'    => $resolved,
				'file'    => $file,
				'line'    => $line,
				'form'    => $form,
				'once'    => '_once' === substr( $form, -5 ),
				'guarded' => self::has_declaration_guard( $tokens, $index ),
			);
		}

		return $includes;
	}

	/**
	 * Determines whether an include is guarded against redeclaring a symbol.
	 *
	 * A guard is a `class_exists()`, `interface_exists()` or `trait_exists()` call
	 * whose second argument is `false`, which suppresses autoloading and so reports
	 * only whether the symbol is already declared. Core writes the guard as
	 * `if ( ! class_exists( 'Name', false ) ) { require ... }`, so the search walks
	 * back over the statement's own condition and stops at the brace or semicolon
	 * that ends whatever precedes it.
	 *
	 * @param array $tokens Tokens of the including file.
	 * @param int   $index  Index of the include token.
	 * @return bool Whether the include is preceded by such a guard.
	 */
	private static function has_declaration_guard( $tokens, $index ) {
		$probes = array( 'class_exists', 'interface_exists', 'trait_exists' );
		$found  = false;

		for ( $cursor = $index - 1; $cursor >= 0; $cursor-- ) {
			$token = $tokens[ $cursor ];

			if ( is_string( $token ) ) {
				// The end of an unrelated statement or block: no guard belongs to this include.
				if ( ';' === $token || '}' === $token ) {
					return false;
				}

				continue;
			}

			if ( T_STRING === $token[0] && in_array( strtolower( $token[1] ), $probes, true ) ) {
				$found = true;
				continue;
			}

			/*
			 * Reaching the `if` that opens the condition ends the search. The guard has
			 * to have been seen inside it, and its second argument has to be false, or
			 * the probe would autoload the very name the include is there to declare.
			 */
			if ( T_IF === $token[0] || T_ELSEIF === $token[0] ) {
				return $found && self::guard_suppresses_autoloading( $tokens, $cursor, $index );
			}
		}

		return false;
	}

	/**
	 * Determines whether every declaration probe in a condition suppresses autoloading.
	 *
	 * @param array $tokens Tokens of the including file.
	 * @param int   $from   Index of the `if` or `elseif` token.
	 * @param int   $to     Index of the include token that follows the condition.
	 * @return bool Whether a probe was found and every one of them passed `false`.
	 */
	private static function guard_suppresses_autoloading( $tokens, $from, $to ) {
		$probes = array( 'class_exists', 'interface_exists', 'trait_exists' );
		$found  = false;

		for ( $cursor = $from; $cursor < $to; $cursor++ ) {
			$token = $tokens[ $cursor ];

			if ( ! is_array( $token ) || T_STRING !== $token[0] || ! in_array( strtolower( $token[1] ), $probes, true ) ) {
				continue;
			}

			$found      = true;
			$arguments  = 0;
			$suppresses = false;

			for ( $inner = $cursor + 1; $inner < $to; $inner++ ) {
				$argument = $tokens[ $inner ];

				if ( is_string( $argument ) ) {
					if ( ',' === $argument ) {
						++$arguments;
						continue;
					}

					if ( ')' === $argument ) {
						break;
					}

					continue;
				}

				if ( 1 === $arguments
					&& T_STRING === $argument[0]
					&& 'false' === strtolower( $argument[1] )
				) {
					$suppresses = true;
				}
			}

			if ( ! $suppresses ) {
				return false;
			}
		}

		return $found;
	}

	/**
	 * Resolves the literal of an include statement to a shipped path.
	 *
	 * Candidates are tried in the order the statement itself implies, and the
	 * first one that names a shipped file wins. The bare literal and the
	 * wp-includes prefixed form are always tried last, so a relative literal is
	 * still resolved when the statement names no constant at all.
	 *
	 * @param string $file       Path of the including file, relative to ABSPATH.
	 * @param string $expression Source of the include expression.
	 * @param string $literal    Literal path taken from the expression.
	 * @param array  $is_shipped Lookup of the shipped paths, keyed by path.
	 * @return string|null Path relative to ABSPATH, or null when none is shipped.
	 */
	private static function resolve_include_target( $file, $expression, $literal, $is_shipped ) {
		$candidates = array();

		if ( false !== strpos( $expression, 'WPINC' ) ) {
			$candidates[] = 'wp-includes/' . $literal;
		}

		if ( false !== strpos( $expression, '__DIR__' ) ) {
			$candidates[] = dirname( $file ) . '/' . $literal;
		}

		$candidates[] = $literal;
		$candidates[] = 'wp-includes/' . $literal;

		foreach ( $candidates as $candidate ) {
			// A concatenation can double a separator, and dirname() returns '.' at the root.
			$candidate = preg_replace( '#/+#', '/', $candidate );
			$candidate = preg_replace( '#(^|/)\./#', '$1', $candidate );

			if ( isset( $is_shipped[ $candidate ] ) ) {
				return $candidate;
			}
		}

		return null;
	}
}
