<?php
/**
 * Core class autoloader.
 *
 * WordPress core has no autoloader: historically every class file reachable on
 * a request was required eagerly from wp-settings.php, so its parse cost was
 * paid even on requests that never referenced it. This file registers a single
 * autoloader so that class, interface and trait files can instead be loaded the
 * first time the name they declare is actually referenced.
 *
 * Resolution is a direct lookup in a generated class map. No path is ever
 * derived from the requested name, and no filter, option, request value or
 * constant other than ABSPATH and WPINC can influence which file is loaded.
 *
 * The class map contract, which the generator and this consumer both honour:
 *
 * - The map lives beside this file and is always read from the hard-coded path
 *   `ABSPATH . WPINC . '/autoload-classmap.php'`.
 * - The map is a PHP file that returns an array keyed by the exact class,
 *   interface or trait name it declares.
 * - Every value is a repository-relative path that begins with `wp-includes/`
 *   and uses forward slashes, for example:
 *
 *       'WP_REST_Posts_Controller' => 'wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php',
 *
 * - A value is therefore resolved as `ABSPATH . $path`, and never as
 *   `ABSPATH . WPINC . '/' . $path`. Keeping the `wp-includes/` prefix inside
 *   the value is what lets one map work unchanged in both the development tree
 *   and the built tree, without the map needing to know the value of WPINC.
 *
 * The map is generated by the `build:autoload-classmap` task in Gruntfile.js.
 * It must not be edited by hand.
 *
 * The map is not read when this file is required. It is loaded lazily on the
 * first autoload miss and then memoized for the rest of the request, so
 * registration costs nothing and requests that reference no mapped name,
 * including SHORTINIT requests, never touch the filesystem for it. When the map
 * is absent, does not return an array, or does not contain the requested name,
 * and when a mapped file has gone away, the autoloader silently does nothing so
 * that every other registered autoloader still gets its turn.
 *
 * @package WordPress
 * @since 7.0.0
 */

/**
 * Loads the file that declares a core class, interface or trait.
 *
 * Registered with spl_autoload_register(), so it runs only when a name that has
 * not been declared yet is referenced. Any name that is absent from the
 * generated class map is ignored without error, which leaves it to the other
 * registered autoloaders.
 *
 * @since 7.0.0
 *
 * @param string $class_name Name of the class, interface or trait to load.
 * @return void
 */
function wp_autoload_class( $class_name ) {
	/*
	 * Null means the map has not been loaded yet, while an array - even an
	 * empty one - means the load has already been attempted. Distinguishing
	 * the two keeps the filesystem check below to one call per request even
	 * when the map is missing or legitimately empty.
	 */
	static $classmap = null;

	if ( null === $classmap ) {
		$classmap      = array();
		$classmap_file = ABSPATH . WPINC . '/autoload-classmap.php';

		if ( file_exists( $classmap_file ) ) {
			$map = require $classmap_file;

			// A map that does not return an array is treated as an empty map.
			if ( is_array( $map ) ) {
				$classmap = $map;
			}
		}
	}

	if ( ! isset( $classmap[ $class_name ] ) ) {
		return;
	}

	$file = ABSPATH . $classmap[ $class_name ];

	if ( ! file_exists( $file ) ) {
		return;
	}

	require $file;
}

spl_autoload_register( 'wp_autoload_class' );
