<?php
/**
 * Core class autoloader.
 *
 * Registers a single autoloader so that the file declaring a core class,
 * interface or trait is loaded the first time that name is referenced, rather
 * than being required in advance from wp-settings.php. Resolution is a direct
 * lookup in a generated class map; no path is derived from the requested name.
 *
 * The map is read from `ABSPATH . WPINC . '/autoload-classmap.php'`, and it is a
 * PHP file returning an array keyed by the lower cased name the mapped file
 * declares:
 *
 *     'wp_rest_posts_controller' => 'wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php',
 *
 * The keys and the lookup are both lower cased because PHP resolves these names
 * case insensitively, and a leading namespace separator is stripped for the same
 * reason. Each value is a canonical repository-relative path with forward
 * slashes, rooted at `wp-includes/` or `wp-admin/includes/` and ending in
 * `.php`; anything else is treated as a miss. A value is resolved as
 * `ABSPATH . $path`, which is what lets one map serve the development tree and
 * the built tree without knowing WPINC, and lets it reach a class outside
 * `wp-includes/`.
 *
 * The map is not read when this file is required: a name outside the prefixes
 * the generator may map returns first, and the first name inside them loads the
 * map for the rest of the request. An absent map, one that returns something
 * other than an array, an unmapped name, a non-canonical path, and a mapped file
 * that has gone away or cannot be read all leave the autoloader doing nothing, so
 * the other registered autoloaders still get their turn. A mapped file that is
 * present and readable but does not compile is the one case that is not absorbed:
 * that is a broken tree rather than a name this autoloader does not own, and it is
 * raised where it happened instead of resurfacing as an unrelated missing class.
 *
 * Doing nothing is the correct response to any one name, but an unusable map is
 * not a fact about one name: no mapped class can load, and the request dies at the
 * first call site that asks for one, naming that class and not this file. So the
 * three faults that make the map itself unusable - missing, present but
 * unreadable, and not returning an array - are written to the error log once per
 * request, naming `autoload-classmap.php` and how to regenerate it, before the
 * autoloader falls back to doing nothing.
 *
 * That fallback is a property of this autoloader, not a promise about the
 * installation. The map is a required part of a WordPress tree exactly as every
 * other file in wp-includes is: with the map gone, the first mapped name the
 * bootstrap itself reaches has nothing to resolve it, and the request ends with
 * PHP's own "class not found" at the line that asked for it - which is why the log
 * line above exists. The build refuses to publish a map it cannot verify, so this
 * is a description of a damaged tree rather than a mode a working one operates in.
 *
 * The map is generated by the `build:autoload-classmap` task in Gruntfile.js and
 * must not be edited by hand. It has to be regenerated when a mapped class is
 * added, moved or renamed, and when a require is added to or removed from
 * wp-settings.php: the bootstrap uses plain `require`, so a name that is both
 * mapped and required eagerly could be autoloaded first and then fatally
 * redeclared.
 *
 * @package WordPress
 * @since 7.0.0
 */

/**
 * Loads the file that declares a core class, interface or trait.
 *
 * Registered with spl_autoload_register(), so it runs only when a name that has
 * not been declared yet is referenced. Any name that is absent from the
 * generated class map is ignored without error, which leaves it to the other
 * registered autoloaders.
 *
 * The name is matched the way PHP resolves it rather than the way it happens to
 * be spelled: a leading namespace separator is dropped and the remainder is
 * lower cased, so `WP_Query`, `wp_query` and `\WP_Query` all reach the same
 * file.
 *
 * @since 7.0.0
 *
 * @param string $class_name Name of the class, interface or trait to load.
 * @return void
 *
 * @throws CompileError When a mapped file is present and readable but does not compile.
 */
function wp_autoload_class( $class_name ) {
	/*
	 * Null means the map has not been loaded yet, while an array - even an
	 * empty one - means the load has already been attempted. Distinguishing
	 * the two keeps the filesystem check below to one call per request even
	 * when the map is missing or legitimately empty.
	 */
	static $classmap = null;

	/*
	 * Prefixes shared by every name the generator is allowed to map. A name that
	 * matches none of them returns before the map is read; a name that does match
	 * reads the map whether or not the map turns out to contain it. The generator
	 * derives the eligible prefixes by reading this declaration and omits any
	 * candidate whose name falls outside them, and Tests_Load_wpAutoloadClass
	 * rejects a committed map that holds a name this list would not admit.
	 */
	static $core_prefixes = array( 'wp', '_wp', 'walker', 'pop3', 'passwordhash', 'requests' );

	/*
	 * PHP passes the name as it was written at the reference site, so `WP_Query`
	 * and `wp_query` both arrive here even though they name one class. The map is
	 * keyed lower cased, so normalising here is what keeps a differently cased
	 * reference from being treated as an unknown name and silently skipped.
	 *
	 * PHP has already removed the one leading separator a fully qualified
	 * reference is written with, so a name that still starts with one reached
	 * spl_autoload_call() directly rather than through a reference. Exactly one
	 * more separator is removed for those callers, and no more: stripping a run of
	 * them would accept a name PHP itself cannot resolve.
	 *
	 * strtr() with explicit ASCII tables rather than strtolower(), which only became
	 * locale independent in PHP 8.2: under an LC_CTYPE such as tr_TR it folds "I"
	 * outside ASCII and would turn a valid reference into a miss on the supported
	 * PHP 7.4 floor.
	 */
	$name = '' !== $class_name && '\\' === $class_name[0] ? substr( $class_name, 1 ) : $class_name;
	$name = strtr( $name, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz' );

	/*
	 * Checked before the map is read, so a name outside the core prefixes costs a
	 * handful of string comparisons rather than loading the class map.
	 */
	$is_core_name = false;

	foreach ( $core_prefixes as $core_prefix ) {
		if ( 0 === strncmp( $name, $core_prefix, strlen( $core_prefix ) ) ) {
			$is_core_name = true;
			break;
		}
	}

	if ( ! $is_core_name ) {
		return;
	}

	if ( null === $classmap ) {
		$classmap       = array();
		$classmap_file  = ABSPATH . WPINC . '/autoload-classmap.php';
		$classmap_fault = '';

		/*
		 * is_readable() rather than file_exists(): a map that exists but cannot be
		 * opened would make the require below raise an uncatchable E_COMPILE_ERROR on
		 * the first core prefixed name of the request, which is the opposite of the
		 * documented behaviour of doing nothing and leaving the name to the other
		 * registered autoloaders.
		 */
		if ( ! is_readable( $classmap_file ) ) {
			$classmap_fault = file_exists( $classmap_file )
				? 'the file is present but could not be opened for reading'
				: 'the file is missing';
		} else {
			$map = require $classmap_file;

			if ( is_array( $map ) ) {
				$classmap = $map;
			} else {
				$classmap_fault = 'the file did not return an array, which is what a truncated or partially written map does';
			}
		}

		/*
		 * Reported because the visible consequence of an unusable map is a fatal
		 * error somewhere else entirely: wp-settings.php no longer requires the
		 * mapped classes, so the request dies at the first call site that asks for
		 * one, naming that class and saying nothing about this file. Without a line
		 * here, the map is the one cause of that fatal which the log never mentions.
		 *
		 * Written to the error log unconditionally rather than through
		 * wp_trigger_error(), which returns early when WP_DEBUG is off - that is the
		 * right behaviour for a developer notice, and the wrong one for an
		 * installation fault that has already made the site unserviceable. This
		 * follows wpdb::print_error(), which likewise logs the fault every time and
		 * gates only whether it is shown. The message is not translated, for the
		 * same reason as that one: it is only ever read in the error log. The path is
		 * relative so the log does not disclose the document root, and the block
		 * runs once per request, so a request that autoloads a hundred names still
		 * reports this once.
		 */
		if ( '' !== $classmap_fault ) {
			error_log(
				sprintf(
					'WordPress could not load %1$s: %2$s. No class listed in that file can be autoloaded, so a "class not found" error naming a core class is a symptom of this rather than of the class itself. Regenerate the map with the build:autoload-classmap Grunt task, or restore the file from a complete copy of this WordPress version.',
					'wp-includes/autoload-classmap.php',
					$classmap_fault
				)
			);
		}
	}

	if ( ! isset( $classmap[ $name ] ) ) {
		return;
	}

	/*
	 * The value is resolved against ABSPATH and then loaded, so it is checked
	 * before it is used rather than trusted for having come from a generated file.
	 * A build that was interrupted, a partially written map, a hand edit or a
	 * tampered tree can all leave a value that is not a path this autoloader owns,
	 * and the only safe response to one is the same as to an unmapped name: do
	 * nothing, and leave the name to the other registered autoloaders.
	 *
	 * The form required is canonical rather than merely plausible. It is rooted at
	 * wp-includes/ or at wp-admin/includes/, every segment is non-empty and begins
	 * with something other than a dot - which is what makes `..`, `.` and the empty
	 * segment of a doubled slash unrepresentable - and it ends in .php with no
	 * backslash and no leading separator anywhere. The generator enforces the same
	 * form when it emits an entry, so neither side depends on the other having got
	 * it right.
	 *
	 * The pattern ends `\.php\z` rather than `\.php$`, because `$` also matches
	 * immediately before a final newline: a value carrying one would otherwise pass a
	 * guard that is advertised as canonical.
	 */
	if ( ! is_string( $classmap[ $name ] )
		|| ! preg_match(
			'#^(?:wp-includes|wp-admin/includes)/(?:[A-Za-z0-9_-][A-Za-z0-9_.-]*/)*[A-Za-z0-9_-][A-Za-z0-9_.-]*\.php\z#',
			$classmap[ $name ]
		)
	) {
		return;
	}

	$file = ABSPATH . $classmap[ $name ];

	/*
	 * is_readable() rather than file_exists(), for the same reason as the map itself:
	 * a mapped file that is present but not readable would raise an E_COMPILE_ERROR
	 * that the catch below cannot reach, because opening the stream fails before any
	 * of the file is compiled.
	 */
	if ( ! is_readable( $file ) ) {
		return;
	}

	/*
	 * Loaded with require_once, because one mapped file can be reached twice in a
	 * request: a caller that probes with class_exists() and then falls through to
	 * interface_exists() autoloads the same name a second time when the file it
	 * loaded did not declare the kind being probed for, and a plain require would
	 * make that second pass a fatal redeclaration instead of a no-op.
	 *
	 * Compiling the file can also fail on something this autoloader does not
	 * control: a declaration whose parent class, interface or trait is not
	 * declared yet raises an Error while the file is being bound. Catching it
	 * leaves the requested name undeclared, which is the same outcome as an
	 * unmapped name - class_exists() answers false and the remaining registered
	 * autoloaders still get their turn. If nothing declares the name, PHP raises
	 * its own "not found" error at the call site that asked for it, where the
	 * missing dependency is visible.
	 *
	 * A CompileError - which ParseError extends - is deliberately not absorbed. It
	 * says the mapped file itself is not valid PHP, so no dependency order and no
	 * other autoloader can satisfy the name, and swallowing it would replace a
	 * report naming the unparsable file with a "class not found" at an unrelated
	 * call site. Re-raising it reproduces what a plain require of the same file
	 * would have done.
	 *
	 * Anything else is reported under WP_DEBUG and absorbed otherwise, so the
	 * fallback stays silent in production while a development install still sees
	 * which mapped file failed and why.
	 */
	try {
		require_once $file;
	} catch ( Error $error ) {
		if ( $error instanceof CompileError ) {
			throw $error;
		}

		if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
			$message = sprintf(
				'%1$s was mapped to %2$s, which could not be loaded: %3$s',
				$class_name,
				$classmap[ $name ],
				$error->getMessage()
			);

			if ( function_exists( 'wp_trigger_error' ) ) {
				wp_trigger_error( 'wp_autoload_class', $message );
			} else {
				// Reached only for a name referenced before functions.php is loaded.
				trigger_error( $message, E_USER_WARNING ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_trigger_error
			}
		}
	}
}

spl_autoload_register( 'wp_autoload_class' );
