<?php
/**
 * Tests for the generated emoji array data file.
 *
 * The region between the markers in wp-includes/emoji-arrays.php is generated by the
 * `replace:emoji-regex` task in Gruntfile.js from a list of file names published by a
 * third party repository, and it is generated as PHP source that the runtime then
 * `require`s. Third party data rewritten into executable source is what these tests
 * hold to being data and nothing but data: every value has to be an HTML entity for a
 * Unicode code point, and the file as a whole has to be incapable of doing anything
 * other than returning two arrays.
 *
 * The generator validates the same grammar before it writes, so a failure here means
 * either that a file was hand-edited - which its header forbids - or that it was
 * generated by something other than the current task. Either way the data has stopped
 * being trustworthy, and it is read on unauthenticated request paths: feeds and
 * outgoing mail both reach `wp_staticize_emoji()`.
 *
 * @package WordPress
 * @subpackage UnitTests
 * @since 7.0.0
 *
 * @group formatting
 * @group emoji
 *
 * @covers ::_wp_emoji_list
 */
class Tests_Formatting_EmojiArrays extends WP_UnitTestCase {

	/**
	 * The generated data file, relative to ABSPATH.
	 *
	 * @var string
	 */
	const DATA_FILE = 'emoji-arrays.php';

	/**
	 * One HTML entity for a Unicode code point, as the generator writes one.
	 *
	 * Lowercase hexadecimal only: that is the form the Twemoji file names are in, and
	 * anything else means a value was not built from a validated file name.
	 *
	 * @var string
	 */
	const CODE_POINT = '&#x[0-9a-f]+;';

	/**
	 * Returns the path of the generated data file.
	 *
	 * @return string Absolute path.
	 */
	private function data_file() {
		return ABSPATH . WPINC . '/' . self::DATA_FILE;
	}

	/**
	 * Returns the data the generated file exports.
	 *
	 * Read with `require` rather than through `_wp_emoji_list()`, so that the file's own
	 * return value is asserted on rather than the runtime's tolerant view of it.
	 *
	 * @return array Generated data.
	 */
	private function data() {
		$this->assertFileExists( $this->data_file(), 'The generated emoji data file must exist.' );

		return require $this->data_file();
	}

	/**
	 * Tests that the generated file exports the two arrays it is required to.
	 */
	public function test_the_data_file_returns_the_two_emoji_arrays() {
		$data = $this->data();

		$this->assertIsArray( $data, 'The generated emoji data file must return an array.' );
		$this->assertSame(
			array( 'entities', 'partials' ),
			array_keys( $data ),
			'The generated emoji data file must return exactly the entities and partials arrays.'
		);

		foreach ( array( 'entities', 'partials' ) as $key ) {
			$this->assertIsArray( $data[ $key ], "The $key value must be an array." );
			$this->assertNotEmpty( $data[ $key ], "The $key array must not be empty." );
			$this->assertSame(
				range( 0, count( $data[ $key ] ) - 1 ),
				array_keys( $data[ $key ] ),
				"The $key array must be a list."
			);
		}
	}

	/**
	 * Tests that every entity is a sequence of code point entities and nothing else.
	 *
	 * An emoji is one or more code points, so an entity is one or more of them run
	 * together. A value that does not match this end to end did not come from a
	 * validated Twemoji file name.
	 */
	public function test_every_entity_is_a_sequence_of_code_points() {
		$data    = $this->data();
		$pattern = '/^(?:' . self::CODE_POINT . ')+$/';

		foreach ( $data['entities'] as $index => $entity ) {
			$this->assertIsString( $entity, "Entity $index must be a string." );
			$this->assertMatchesRegularExpression(
				$pattern,
				$entity,
				"Entity $index must be a sequence of lowercase hexadecimal code point entities."
			);
		}
	}

	/**
	 * Tests that every partial is exactly one code point entity.
	 */
	public function test_every_partial_is_a_single_code_point() {
		$data    = $this->data();
		$pattern = '/^' . self::CODE_POINT . '$/';

		foreach ( $data['partials'] as $index => $partial ) {
			$this->assertIsString( $partial, "Partial $index must be a string." );
			$this->assertMatchesRegularExpression(
				$pattern,
				$partial,
				"Partial $index must be a single lowercase hexadecimal code point entity."
			);
		}
	}

	/**
	 * Tests that no value carries a character that means something to PHP or to HTML.
	 *
	 * The grammar asserted above already excludes all of these. They are named
	 * individually as well, because these are the characters that would let a value
	 * escape the single quoted PHP literal it is written in, or the attribute that
	 * `wp_staticize_emoji()` later writes it into.
	 */
	public function test_no_value_carries_a_character_with_meaning() {
		$data      = $this->data();
		$forbidden = array( "'", '"', '\\', '<', '>', '$', '(', ')', '`', ' ', "\0", "\r", "\n" );

		foreach ( array( 'entities', 'partials' ) as $key ) {
			foreach ( $data[ $key ] as $index => $value ) {
				foreach ( $forbidden as $character ) {
					$this->assertStringNotContainsString(
						$character,
						$value,
						sprintf(
							'%s %d must not carry %s.',
							$key,
							$index,
							wp_json_encode( $character )
						)
					);
				}
			}
		}
	}

	/**
	 * Tests that the generated file can do nothing but return its two arrays.
	 *
	 * The grammar tests above cover the values. This covers the file, by tokenizing it
	 * and requiring every token to be one that assembling two arrays of string literals
	 * needs. A call, an assignment to anything but the two expected variables, an array
	 * subscript, a string interpolation or a second open tag all introduce a token that
	 * is not on this list, so this is what makes "data only" a property of the file
	 * rather than a property of the values it happens to hold today.
	 */
	public function test_the_data_file_is_data_only() {
		$tokens = token_get_all( file_get_contents( $this->data_file() ) );

		$allowed_tokens = array(
			T_OPEN_TAG,
			T_DOC_COMMENT,
			T_COMMENT,
			T_WHITESPACE,
			T_VARIABLE,
			T_ARRAY,
			T_CONSTANT_ENCAPSED_STRING,
			T_DOUBLE_ARROW,
			T_RETURN,
		);

		$allowed_characters = array( '=', '(', ')', ',', ';' );

		$variables = array();

		foreach ( $tokens as $token ) {
			if ( is_array( $token ) ) {
				$this->assertContains(
					$token[0],
					$allowed_tokens,
					sprintf(
						'The generated emoji data file must not use %s (line %d).',
						token_name( $token[0] ),
						$token[2]
					)
				);

				if ( T_VARIABLE === $token[0] ) {
					$variables[ $token[1] ] = true;
				}

				continue;
			}

			$this->assertContains(
				$token,
				$allowed_characters,
				sprintf( 'The generated emoji data file must not use the %s character.', $token )
			);
		}

		$this->assertSame(
			array( '$entities', '$partials' ),
			array_keys( $variables ),
			'The generated emoji data file must name no variables other than the two arrays.'
		);
	}

	/**
	 * Tests that the runtime hands back exactly what the generated file exports.
	 *
	 * `_wp_emoji_list()` is deliberately tolerant of a missing or malformed data file,
	 * so this confirms that with the shipped file in place it is not substituting or
	 * filtering anything: what the tests above assert about the file is therefore also
	 * true of what every caller receives.
	 */
	public function test_the_runtime_returns_the_generated_data() {
		$data = $this->data();

		$this->assertSame( $data['entities'], _wp_emoji_list( 'entities' ), 'The entities list must be returned as generated.' );
		$this->assertSame( $data['partials'], _wp_emoji_list( 'partials' ), 'The partials list must be returned as generated.' );
	}

	/**
	 * Tests that the generated file still carries the markers the generator needs.
	 *
	 * `replace:emoji-regex` finds the region to rewrite by matching these two comments.
	 * If either one is lost the task matches nothing, and `pedantic: true` is what turns
	 * that into a failed build rather than a silent no-op - but only if the markers are
	 * the exact text the task looks for.
	 *
	 * The header is asserted alongside them, because it is the only thing telling a reader
	 * that the region is regenerated and which task to run. It names `precommit:emoji`,
	 * the task that runs `replace:emoji-regex` after verifying the markers.
	 */
	public function test_the_data_file_carries_the_generator_markers() {
		$source = file_get_contents( $this->data_file() );
		$start  = strpos( $source, '// START: emoji arrays' );

		/*
		 * The assertions below deliberately reduce the file to a boolean or to its
		 * header before asserting. The data region is over 140KB on a handful of
		 * physical lines, so asserting against the whole string would print all of
		 * it on failure and bury the diagnostic.
		 */
		$this->assertNotFalse( $start, 'The opening marker must be present.' );
		$this->assertNotFalse( strpos( $source, '// END: emoji arrays' ), 'The closing marker must be present.' );

		/*
		 * The header is a wrapped doc comment, so it is flattened before it is searched.
		 * A phrase asserted against the raw source would fail the moment a rewrap split it
		 * across two lines, which says nothing about what the header actually states.
		 */
		$header = trim( preg_replace( '/\s+/', ' ', str_replace( '*', ' ', substr( $source, 0, $start ) ) ) );

		$this->assertStringContainsString(
			'generated by the `precommit:emoji` task',
			$header,
			'The generated file must name the task that generates its data region.'
		);
		$this->assertStringContainsString(
			'must not be edited manually',
			$header,
			'The generated file must say that its data region is not to be edited by hand.'
		);
	}
}
